(()=>{'use strict';
const breeds=[
['Maine Coon','long','Grand','5–9 kg','Modérée','Grand chat sociable, joueur et généralement doux.','Patient, affectueux, adaptable','Espace vertical solide, brossage régulier et présence quotidienne. Convient à une famille disponible.','Son pelage et sa grande taille demandent un suivi attentif; dépistage cardiaque recommandé.'],
['Ragdoll','long','Grand','4–9 kg','Modérée','Chat calme, proche de l’humain et réputé détendu.','Doux, sociable, posé','Vie intérieure enrichie, compagnie et brossage fréquent. Idéal pour un foyer calme et présent.','Il supporte mal les longues absences et son poil doit être entretenu.'],
['Bengal','short','Moyen','4–7 kg','Très élevée','Athlétique, curieux et très intelligent.','Joueur, vif, expressif','Beaucoup de jeux, hauteur, entraînement et interactions. Pour une personne très active.','L’ennui peut provoquer des comportements difficiles; ce n’est pas un chat décoratif.'],
['Siamois','short','Moyen','3–6 kg','Élevée','Très communicatif et fortement attaché à ses humains.','Intelligent, affectueux, interactif','Présence importante, jeux et conversations quotidiennes.','Il peut être vocal et vivre difficilement la solitude.'],
['British Shorthair','short','Moyen','4–8 kg','Modérée','Calme, solide et plutôt indépendant sans être distant.','Paisible, stable, adaptable','Jeu quotidien modéré et contrôle du poids. Adapté à l’appartement enrichi.','Tendance à l’embonpoint; il n’aime pas toujours être porté.'],
['Sphynx','none','Moyen','3–5 kg','Élevée','Chat sans fourrure, chaleureux et très proche de l’humain.','Sociable, drôle, câlin','Chaleur, nettoyage régulier de la peau et présence.','Il n’est pas hypoallergénique; peau, oreilles et température exigent des soins.'],
['Persan','long','Moyen','3–6 kg','Faible','Chat tranquille au long pelage abondant.','Calme, tendre, discret','Brossage quotidien, nettoyage des yeux et maison paisible.','Les faces très aplaties sont liées à des difficultés respiratoires et oculaires.'],
['Abyssin','short','Moyen','3–5 kg','Très élevée','Explorateur agile qui aime participer à la vie du foyer.','Curieux, intelligent, joueur','Parcours en hauteur, jeux variés et interactions fréquentes.','Peut mal vivre l’inactivité et les longues périodes seul.'],
['Sacré de Birmanie','long','Moyen','4–7 kg','Modérée','Équilibré, affectueux et sociable.','Doux, patient, proche','Brossage hebdomadaire, jeu et compagnie régulière.','Demande une présence affective et un suivi du poids.'],
['Bleu russe','short','Moyen','3–6 kg','Modérée','Fin, réservé avec les inconnus et fidèle à son foyer.','Calme, propre, loyal','Routine stable, cachettes et approche douce.','Sensible au bruit et aux changements brusques.'],
['Norvégien','long','Grand','4–9 kg','Élevée','Grand grimpeur rustique au pelage double.','Sociable, agile, équilibré','Arbres à chat robustes, jeu et brossage accru en mue.','Sa taille exige un matériel solide et un suivi articulaire.'],
['Sibérien','long','Grand','4–9 kg','Élevée','Puissant, joueur et généralement sociable.','Affectueux, robuste, adaptable','Jeu actif, hauteur et brossage régulier.','Aucune race n’est réellement hypoallergénique.'],
['Chartreux','short','Moyen','3–7 kg','Modérée','Chat français calme, observateur et musclé.','Paisible, loyal, discret','Jeu quotidien et alimentation mesurée.','Sa discrétion peut masquer une douleur; surveiller les changements.'],
['Devon Rex','curly','Petit','2.5–4.5 kg','Élevée','Petit chat vif au poil ondulé et aux grandes oreilles.','Espiègle, sociable, câlin','Chaleur, jeux, compagnie et soins délicats du pelage.','Peau et oreilles demandent une attention régulière.'],
['Cornish Rex','curly','Petit','2.5–4.5 kg','Très élevée','Athlétique au pelage très court et ondulé.','Joueur, affectueux, énergique','Maison chaude, activités et présence importantes.','Sensible au froid et souvent très actif.'],
['Scottish Fold','short','Moyen','3–6 kg','Modérée','Chat reconnaissable à ses oreilles pliées.','Doux, calme, sociable','Foyer tranquille et suivi vétérinaire rigoureux.','Le pli des oreilles vient d’une mutation touchant le cartilage et peut causer douleur et maladie articulaire.'],
['Oriental Shorthair','short','Moyen','3–6 kg','Élevée','Élancé, bavard et intensément sociable.','Intelligent, affectueux, curieux','Beaucoup d’interactions et de stimulation mentale.','Supporte mal la solitude et peut être très vocal.'],
['Angora turc','long','Moyen','3–5 kg','Élevée','Élégant, agile et volontaire.','Joueur, intelligent, proche','Hauteur, jeu, brossage et respect de son autonomie.','Peut avoir un caractère affirmé; certains chats blancs sont sourds.'],
['Bombay','short','Moyen','3–6 kg','Modérée','Chat noir sociable au tempérament souvent joueur.','Affectueux, adaptable, curieux','Compagnie, jeu quotidien et vie intérieure stimulante.','Surveiller le poids et choisir un élevage attentif à la santé.'],
['Burmese','short','Moyen','3–6 kg','Élevée','Très humain, joueur et confiant.','Sociable, malin, tendre','Présence fréquente et activités partagées.','Supporte difficilement la solitude prolongée.']
].map((x,i)=>({id:i,name:x[0],coat:x[1],size:x[2],weight:x[3],activity:x[4],summary:x[5],qualities:x[6],needs:x[7],know:x[8]}));
const english={
'Maine Coon':['Large, social and playful cat with a typically gentle nature.','Patient, affectionate, adaptable','Strong climbing structures, regular brushing and daily company. Suits an available family.','Its coat and large build require attentive care; heart screening is recommended.'],
'Ragdoll':['Calm, people-oriented cat known for its relaxed nature.','Gentle, social, composed','An enriched indoor life, companionship and frequent brushing. Best in a calm, present home.','Long absences can be difficult and its coat needs maintenance.'],
'Bengal':['Athletic, curious and highly intelligent.','Playful, lively, expressive','Plenty of games, climbing, training and interaction. Best for a very active person.','Boredom may lead to difficult behaviour; this is not a decorative cat.'],
'Siamois':['Very communicative and strongly attached to its people.','Intelligent, affectionate, interactive','Frequent company, play and daily interaction.','May be very vocal and can struggle with loneliness.'],
'British Shorthair':['Calm, sturdy and fairly independent without being distant.','Peaceful, steady, adaptable','Moderate daily play and weight management. Suits an enriched apartment.','Prone to weight gain and does not always enjoy being carried.'],
'Sphynx':['Hairless, warm-seeking and very people-oriented.','Social, funny, cuddly','Warmth, regular skin cleaning and company.','Not hypoallergenic; skin, ears and body temperature need special care.'],
'Persan':['Quiet cat with a very long, abundant coat.','Calm, tender, discreet','Daily brushing, eye cleaning and a peaceful home.','Very flat faces are associated with breathing and eye problems.'],
'Abyssin':['Agile explorer that likes taking part in home life.','Curious, intelligent, playful','Climbing routes, varied games and frequent interaction.','May struggle with inactivity and long periods alone.'],
'Sacré de Birmanie':['Balanced, affectionate and sociable.','Gentle, patient, close','Weekly brushing, play and regular company.','Needs affectionate presence and weight monitoring.'],
'Bleu russe':['Refined, reserved with strangers and loyal to its home.','Calm, clean, loyal','A stable routine, hiding places and a gentle approach.','Sensitive to noise and sudden changes.'],
'Norvégien':['Large, hardy climber with a thick double coat.','Social, agile, balanced','Strong cat trees, play and extra brushing while shedding.','Its size requires sturdy equipment and joint monitoring.'],
'Sibérien':['Powerful, playful and generally sociable.','Affectionate, sturdy, adaptable','Active play, climbing and regular brushing.','No cat breed is truly hypoallergenic.'],
'Chartreux':['Calm, observant and muscular French breed.','Peaceful, loyal, discreet','Daily play and measured meals.','Its quiet nature can hide pain; monitor behavioural changes.'],
'Devon Rex':['Small, lively cat with a wavy coat and large ears.','Mischievous, social, cuddly','Warmth, games, company and gentle coat care.','Skin and ears need regular attention.'],
'Cornish Rex':['Athletic cat with a very short, wavy coat.','Playful, affectionate, energetic','A warm home, activities and plenty of company.','Sensitive to cold and often highly active.'],
'Scottish Fold':['Cat recognized by its folded ears.','Gentle, calm, social','A quiet home and rigorous veterinary monitoring.','The ear fold comes from a cartilage mutation that can cause painful joint disease.'],
'Oriental Shorthair':['Slender, talkative and intensely social.','Intelligent, affectionate, curious','Plenty of interaction and mental stimulation.','Struggles with loneliness and may be very vocal.'],
'Angora turc':['Elegant, agile and strong-willed.','Playful, intelligent, close','Climbing, play, brushing and respect for its independence.','Can be assertive; some white cats are deaf.'],
'Bombay':['Social black cat with a commonly playful temperament.','Affectionate, adaptable, curious','Company, daily play and a stimulating indoor life.','Monitor weight and choose a health-conscious breeder.'],
'Burmese':['Very people-oriented, playful and confident.','Social, clever, tender','Frequent company and shared activities.','Usually struggles with prolonged solitude.']};
const $=id=>document.getElementById(id),grid=$('breedGrid'),search=$('search'),coat=$('coat'),modal=$('modal');let lang=localStorage.getItem('dicopetsLanguage')||'fr';
const coatName=v=>({short:['Poil court','Short coat'],long:['Poil long','Long coat'],curly:['Poil frisé','Curly coat'],none:['Sans poil','Hairless']}[v][lang==='en'?1:0]);
const sizeName=v=>lang==='en'?({Petit:'Small',Moyen:'Medium',Grand:'Large'}[v]||v):v,activityName=v=>lang==='en'?({Faible:'Low',Modérée:'Moderate',Élevée:'High','Très élevée':'Very high'}[v]||v):v,profile=b=>lang==='en'?(english[b.name]||[b.summary,b.qualities,b.needs,b.know]):[b.summary,b.qualities,b.needs,b.know];
function render(){const q=search.value.trim().toLowerCase(),list=breeds.filter(b=>(coat.value==='all'||b.coat===coat.value)&&(!q||(b.name+' '+b.summary+' '+b.qualities).toLowerCase().includes(q)));grid.innerHTML=list.map(b=>`<article class="card"><div class="card-top"><h3>${b.name}</h3><span class="badge">${coatName(b.coat)}</span></div><p>${profile(b)[0]}</p><div class="facts"><div class="fact"><strong>${lang==='en'?'Size':'Taille'}</strong>${sizeName(b.size)}</div><div class="fact"><strong>${lang==='en'?'Weight':'Poids'}</strong>${b.weight}</div></div><button class="open" data-id="${b.id}" type="button">${lang==='en'?'Open profile':'Voir la fiche'}</button></article>`).join('')||`<p>${lang==='en'?'No breed found.':'Aucune race trouvée.'}</p>`;grid.querySelectorAll('.open').forEach(x=>x.onclick=()=>openBreed(breeds[+x.dataset.id]))}
function openBreed(b){const p=profile(b);$('mBadge').textContent=coatName(b.coat);$('mTitle').textContent=b.name;$('mSummary').textContent=p[0];$('mHeight').textContent=sizeName(b.size);$('mWeight').textContent=b.weight;$('mActivity').textContent=activityName(b.activity);$('mCoat').textContent=coatName(b.coat);$('mQualities').textContent=p[1];$('mNeeds').textContent=p[2];$('mKnow').textContent=p[3];$('google').textContent=lang==='en'?'Search this breed on Google ↗':'Rechercher cette race sur Google ↗';$('close').textContent=lang==='en'?'Close ×':'Fermer ×';$('google').href='https://www.google.com/search?tbm=isch&q='+encodeURIComponent(b.name+' cat breed');modal.classList.add('open');document.body.classList.add('modal-open')}
$('close').onclick=()=>{modal.classList.remove('open');document.body.classList.remove('modal-open')};modal.onclick=e=>{if(e.target===modal)$('close').click()};search.oninput=render;coat.onchange=render;
const language=$('language');language.value=lang;function translate(){lang=language.value;localStorage.setItem('dicopetsLanguage',lang);document.documentElement.lang=lang;document.querySelectorAll('[data-fr]').forEach(el=>el.textContent=el.dataset[lang]);search.placeholder=lang==='en'?'Search a breed…':'Rechercher une race…';coat.options[0].text=lang==='en'?'All coats':'Tous les pelages';coat.options[1].text=lang==='en'?'Short coat':'Poil court';coat.options[2].text=lang==='en'?'Long coat':'Poil long';coat.options[3].text=lang==='en'?'Curly coat':'Poil frisé';coat.options[4].text=lang==='en'?'Hairless':'Sans poil';render()}language.onchange=translate;translate();
})();
