(() => {
  const $ = selector => document.querySelector(selector);
  const db = window.supabase?.createClient('https://mmxdlnfntpufwwkdvgzc.supabase.co', 'sb_publishable_Pa-DX3nwNTZktbWK46KDQg_IuIy8TZP');
  const en = () => document.documentElement.lang === 'en-US' || localStorage.getItem('dicochevalLocale') === 'en-US';
  const t = (fr, english) => en() ? english : fr;
  const countries = [
    ['France',49,38,['Selle français','Camargue','Percheron','Comtois','Trait breton','Henson','Landais','Pottok']],['Espagne',46.5,43,['Andalou','Pottok']],['Portugal',45.5,44,['Lusitanien']],['Royaume-Uni',47.5,30,['Pur-sang anglais','Clydesdale','Dartmoor','Exmoor','Fell','Highland','New Forest','Shetland','Welsh']],['Irlande',45,32,['Irish Cob','Connemara','Kerry Bog']],['Islande',42,23,['Islandais']],['Allemagne',51,36,['Hanovrien','Holsteiner','Trakehner']],['Pays-Bas',49.5,34,['Frison','KWPN']],['Belgique',49,36.5,['Trait belge','Zangersheide']],['Autriche',52.5,42,['Haflinger']],['Norvège',50,25,['Fjord']],['Suède',53,28,['Gotland']],['Hongrie',54,42,['Shagya']],['Tchéquie',53,39,['Kinsky']],['Maroc',47.5,51,['Barbe']],['Algérie',50,52,['Barbe']],['États-Unis',22,40,['Appaloosa','Mustang','Paint Horse','Quarter Horse','Tennessee Walker']],['Canada',20,25,['Lac La Croix']],['Argentine',31,76,['Criollo']],['Turkménistan',63,43,['Akhal-Téké']],['Mongolie',73,40,['Mongol']],['Japon',83,43,['Hokkaido']],['Australie',84,73,['Australien']]
  ];
  const map = document.createElement('section'); map.id='carte-races'; map.className='section map-section';
  map.innerHTML='<div class="wrap"><div class="head"><h2></h2><p></p></div><div class="map-layout"><div><div class="world-map" role="group" aria-label="Carte du monde des races"><img src="https://upload.wikimedia.org/wikipedia/commons/a/ac/World_location_map.svg" alt="Carte du monde"><div class="map-pins"></div></div><div class="map-controls"><button type="button" class="show-countries"></button><span class="map-progress"></span></div><p class="map-credit">Carte : <a href="https://commons.wikimedia.org/wiki/File:World_location_map.svg" target="_blank" rel="noopener">Wikimedia Commons</a> · domaine public</p></div><article class="map-result"><span class="eyebrow"></span><h3></h3><p></p><div class="map-breeds"></div></article></div></div>';
  $('#races')?.before(map);
  const ideal=document.createElement('section'); ideal.id='cheval-ideal'; ideal.className='section rose'; ideal.innerHTML='<div class="wrap"><div class="head"><h2></h2><p></p></div><div class="ideal-card"><div class="ideal-questions"></div><button class="ideal-submit"></button><div class="ideal-result" aria-live="polite"></div></div></div>'; $('#disciplines')?.before(ideal);
  const badges=document.createElement('section'); badges.id='badges'; badges.className='section tint'; badges.innerHTML='<div class="wrap"><div class="head"><h2></h2><p></p></div><div class="badge-grid"></div></div>'; $('#quiz')?.before(badges);
  document.head.insertAdjacentHTML('beforeend','<style>.map-layout{display:grid;grid-template-columns:1.25fr .75fr;gap:22px;align-items:start}.world-map{position:relative;overflow:hidden;border-radius:18px;background:#bcd8e8;box-shadow:0 9px 25px #17352622;aspect-ratio:2/1}.world-map>img{display:block;width:100%;height:100%;object-fit:cover}.map-pins{position:absolute;inset:0}.map-pin{position:absolute;left:calc(var(--x) * 1%);top:calc(var(--y) * 1%);translate:-50% -50%;padding:5px 8px!important;border:2px solid #fff!important;border-radius:99px!important;background:#234f3a!important;color:#fff!important;font-size:11px!important;font-weight:800!important;line-height:1.1!important;box-shadow:0 2px 7px #17352677;cursor:pointer}.map-pin:hover,.map-pin.active{background:#b58a4b!important;transform:scale(1.08)}.map-controls{display:flex;gap:12px;align-items:center;margin-top:13px}.show-countries{padding:9px 13px!important;font-size:13px!important}.map-progress{font-size:13px;color:#50685d}.map-credit{font-size:12px;color:#63756a;margin:10px 2px}.map-credit a{color:#234238}.map-result,.ideal-card{background:#fffdf8;border:1px solid #d7e0d5;border-radius:18px;padding:27px}.map-result h3{margin:5px 0;color:#1f4737}.eyebrow{font-size:12px;color:#b58a4b;font-weight:900;text-transform:uppercase;letter-spacing:.12em}.map-breeds{display:flex;flex-wrap:wrap;gap:8px;margin-top:18px}.map-breeds button{background:#e4eee7!important;color:#1f4737!important;border:0;border-radius:99px;padding:8px 12px;font-weight:800}.ideal-questions{display:grid;grid-template-columns:repeat(3,1fr);gap:15px}.ideal-questions label{font-weight:800;color:#1f4737}.ideal-questions select{display:block;width:100%;margin-top:7px;padding:11px;border:1px solid #cbd8ce;border-radius:10px;background:white}.ideal-submit{margin-top:22px}.ideal-result{margin-top:22px;display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.match{background:#edf2ea;border-radius:12px;padding:17px}.match h3{margin:0;color:#1f4737}.match button{padding:7px 10px;margin-top:10px}.badge-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.badge{background:white;border:1px solid #d7e0d5;border-radius:16px;padding:21px;opacity:.48}.badge.unlocked{opacity:1;border-color:#b58a4b;box-shadow:0 8px 22px #1f47371a}.badge .medal{font-size:31px}.badge h3{margin:10px 0 6px;color:#1f4737}.badge small{color:#63756a}@media(max-width:720px){.map-layout,.ideal-questions,.ideal-result{grid-template-columns:1fr}.badge-grid{grid-template-columns:1fr 1fr}.map-pin{font-size:9px!important;padding:4px 6px!important}.map-controls{align-items:flex-start;flex-direction:column}}</style>');
  const badgeInfo={world:['🌍',()=>t('Explorateur du monde','World explorer'),()=>t('Explore 5 pays différents sur la carte','Explore 5 different countries on the map')],finder:['✨',()=>t('Mon cheval idéal','My ideal horse'),()=>t('Termine le questionnaire','Complete the questionnaire')],breed:['🐴',()=>t('Passionné de races','Breed enthusiast'),()=>t('Ouvre une fiche de race','Open a breed profile')],quiz:['🏆',()=>t('Quiz terminé','Quiz complete'),()=>t('Réponds aux 30 questions du quiz','Answer all 30 quiz questions')]};
  const badgesList=()=>JSON.parse(localStorage.getItem('dcBadges')||'[]'), visited=()=>JSON.parse(localStorage.getItem('dcVisitedCountries')||'[]');
  async function saveBadges(list){if(!db)return;const {data}=await db.auth.getUser();if(data.user)await db.auth.updateUser({data:{badges:list}})}
  function unlock(key){const list=badgesList();if(!list.includes(key)){list.push(key);localStorage.setItem('dcBadges',JSON.stringify(list));saveBadges(list)}window.dispatchEvent(new Event('dc-badges-changed'));renderBadges()}
  function visitCountry(name){const list=visited();if(!list.includes(name)){list.push(name);localStorage.setItem('dcVisitedCountries',JSON.stringify(list))}if(list.length>=5)unlock('world')}
  function showCountry(country,pin){document.querySelectorAll('.map-pin').forEach(x=>x.classList.remove('active'));pin?.classList.add('active');visitCountry(country[0]);const list=country[3];$('.map-result .eyebrow').textContent=t('Races liées à ce pays','Breeds connected to this country');$('.map-result h3').textContent=country[0];$('.map-result p').textContent=t(`${list.length} races à découvrir.`,`${list.length} breeds to discover.`);$('.map-breeds').innerHTML=list.map(name=>`<button type="button" data-breed="${name}">${name}</button>`).join('');document.querySelectorAll('.map-breeds button').forEach(button=>button.onclick=()=>window.openBreed?.(button.dataset.breed));renderProgress()}
  function renderMap(){const expanded=localStorage.getItem('dcAllMapCountries')==='1',visible=expanded?countries:countries.slice(0,12);$('.map-pins').innerHTML=visible.map(c=>`<button type="button" class="map-pin" style="--x:${c[1]};--y:${c[2]}" data-country="${c[0]}">${c[0]}</button>`).join('');document.querySelectorAll('.map-pin').forEach(pin=>pin.onclick=()=>showCountry(countries.find(c=>c[0]===pin.dataset.country),pin));const toggle=$('.show-countries');toggle.textContent=expanded?t('Voir moins de pays','Show fewer countries'):t(`Voir les ${countries.length-12} autres pays`,`Show ${countries.length-12} more countries`);toggle.onclick=()=>{localStorage.setItem('dcAllMapCountries',expanded?'0':'1');renderMap()};renderProgress()}
  function renderProgress(){$('.map-progress').textContent=t(`${visited().length}/5 pays explorés`,`${visited().length}/5 countries explored`)}
  function findIdeal(){const a=$('#ideal0').value,b=$('#ideal1').value,c=$('#ideal2').value,picks=c==='pony'?['Connemara','Haflinger','New Forest']:b==='jump'||a==='sport'?['Selle français','Hanovrien','Quarter Horse']:b==='outdoor'?['Mérens','Islandais','Appaloosa']:['Haflinger','Franche-Montagne','Camargue'];$('.ideal-result').innerHTML=picks.map(name=>`<article class="match"><span>★ ${t('Bonne piste','Great match')}</span><h3>${name}</h3><button type="button" data-breed="${name}">${t('Voir la fiche','View profile')}</button></article>`).join('');document.querySelectorAll('.ideal-result button').forEach(button=>button.onclick=()=>window.openBreed?.(button.dataset.breed));unlock('finder')}
  function renderBadges(){const list=badgesList();$('.badge-grid').innerHTML=Object.entries(badgeInfo).map(([key,item])=>`<article class="badge ${list.includes(key)?'unlocked':''}"><div class="medal">${item[0]}</div><h3>${item[1]()}</h3><small>${item[2]()}</small><p>${list.includes(key)?t('Débloqué !','Unlocked!'):t('À débloquer','Locked')}</p></article>`).join('')}
  function render(){document.querySelectorAll('.nav .wrap').forEach(nav=>{if(!nav.querySelector('[href="#carte-races"]'))nav.insertAdjacentHTML('beforeend',`<a href="#carte-races">${t('Carte','Map')}</a><a href="#cheval-ideal">${t('Mon cheval','My horse')}</a><a href="#badges">${t('Badges','Badges')}</a>`)});$('#carte-races h2').textContent=t('Carte des races','Breed map');$('#carte-races .head p').textContent=t('Clique sur un pays de la carte du monde, puis sur une race pour ouvrir sa fiche.','Click a country on the world map, then a breed to open its profile.');$('#cheval-ideal h2').textContent=t('Mon cheval idéal','My ideal horse');$('#cheval-ideal .head p').textContent=t('Réponds à trois questions : le site te propose des races à explorer.','Answer three questions and discover breeds to explore.');$('#badges h2').textContent=t('Mes badges','My badges');$('#badges .head p').textContent=t('Découvre le site et collectionne tes badges.','Explore the site and collect badges.');$('.ideal-questions').innerHTML=[[t('Expérience','Experience'),[['beginner',t('Je débute','I am a beginner')],['regular',t('J’ai un peu d’expérience','Some experience')],['sport',t('Je veux pratiquer un sport','I want to do sport')]]],[t('Ce que je préfère','What I prefer'),[['calm',t('Calme et proche de l’humain','Calm and people-oriented')],['outdoor',t('Randonnée et extérieur','Trail riding')],['jump',t('Saut et polyvalence','Jumping and versatility')]]],[t('Taille souhaitée','Preferred size'),[['pony',t('Poney','Pony')],['medium',t('Moyen','Medium')],['large',t('Grand cheval','Large horse')]]]].map(([label,options],index)=>`<label>${label}<select id="ideal${index}">${options.map(option=>`<option value="${option[0]}">${option[1]}</option>`).join('')}</select></label>`).join('');$('.ideal-submit').textContent=t('Trouver mes races','Find my breeds');$('.ideal-submit').onclick=findIdeal;renderMap();renderBadges()}
  const oldOpen=window.openBreed;if(oldOpen)window.openBreed=function(name){unlock('breed');return oldOpen(name)};const answered=new Set(JSON.parse(localStorage.getItem('dcQuizQuestions')||'[]')),oldAnswer=window.answer;if(oldAnswer)window.answer=function(element){const number=document.querySelector('#quiz [data-question]')?.dataset.question||document.querySelector('#quiz h2')?.textContent||String(answered.size);answered.add(String(number));localStorage.setItem('dcQuizQuestions',JSON.stringify([...answered]));const result=oldAnswer(element);if(answered.size>=30)unlock('quiz');return result};render();document.getElementById('locale')?.addEventListener('change',()=>setTimeout(render,10));
})();
