(()=>{'use strict';const $=id=>document.getElementById(id),db=window.supabase.createClient('https://mmxdlnfntpufwwkdvgzc.supabase.co','sb_publishable_Pa-DX3nwNTZktbWK46KDQg_IuIy8TZP');let user=null,entries=[],events=[];const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(){ $('entries').innerHTML=entries.slice().reverse().map(x=>`<article class="entry"><button class="delete" data-entry="${x.id}">×</button><h3>${esc(x.title)}</h3><small>${new Date(x.created).toLocaleDateString('fr-CA')}</small><p>${esc(x.text)}</p></article>`).join('')||'<p>Aucune page enregistrée.</p>';$('events').innerHTML=events.slice().sort((a,b)=>a.date.localeCompare(b.date)).map(x=>`<article class="entry"><button class="delete" data-event="${x.id}">×</button><h3>${esc(x.title)}</h3><small>${esc(x.date)} ${esc(x.time)}</small></article>`).join('')||'<p>Aucun événement.</p>';document.querySelectorAll('[data-entry]').forEach(b=>b.onclick=()=>{entries=entries.filter(x=>x.id!==b.dataset.entry);save()});document.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>{events=events.filter(x=>x.id!==b.dataset.event);window.DicoPetsNotifications?.remove('cat-'+b.dataset.event);save()})}
async function save(){if(!user)return;await db.auth.updateUser({data:{cat_journal_entries:entries.slice(-50),cat_calendar_events:events.slice(-50)}});render()}
function open(u){user=u;entries=u.user_metadata?.cat_journal_entries||[];events=u.user_metadata?.cat_calendar_events||[];$('loginBox').classList.add('hidden');$('privateArea').classList.remove('hidden');$('memberName').textContent=u.user_metadata?.pseudo||u.email;render();events.forEach(schedule)}function close(){$('loginBox').classList.remove('hidden');$('privateArea').classList.add('hidden');user=null}
$('login').onclick=async()=>{const {data,error}=await db.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});$('message').textContent=error?error.message:'';if(data.user)open(data.user)};$('logout').onclick=async()=>{await db.auth.signOut();close()};
$('saveEntry').onclick=()=>{const title=$('entryTitle').value.trim(),text=$('entryText').value.trim();if(!title||!text)return;entries.push({id:crypto.randomUUID(),title,text,created:new Date().toISOString()});$('entryTitle').value=$('entryText').value='';save()};
function schedule(x){if(!x.date)return;const when=new Date(`${x.date}T${x.time||'09:00'}`);when.setHours(when.getHours()-1);window.DicoPetsNotifications?.schedule({id:'cat-'+x.id,title:'Rappel DicoChat',body:x.title,when:when.getTime(),url:'journal-chat.html'})}
$('saveEvent').onclick=()=>{const title=$('eventTitle').value.trim(),date=$('eventDate').value,time=$('eventTime').value;if(!title||!date)return;const x={id:crypto.randomUUID(),title,date,time};events.push(x);schedule(x);$('eventTitle').value=$('eventDate').value=$('eventTime').value='';save()};$('enableNotifications').onclick=async()=>{const result=await window.DicoPetsNotifications.enable();$('notificationStatus').textContent=result.message};
db.auth.getSession().then(({data})=>data.session?.user?open(data.session.user):close());db.auth.onAuthStateChange((_e,s)=>s?.user?open(s.user):close());
})();
