(()=>{
  const $=id=>document.getElementById(id),fields=['date','horse','activity','mood','notes','goal'];
  const db=window.supabase.createClient('https://mmxdlnfntpufwwkdvgzc.supabase.co','sb_publishable_Pa-DX3nwNTZktbWK46KDQg_IuIy8TZP');
  let user=null,entries=[],currentEntry=null;
  $('date').valueAsDate=new Date();
  const escape=s=>String(s||'').replace(/[&<>]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[x]));
  const status=(message,ok=false)=>$('status').innerHTML=ok?'<span class="saved">'+message+'</span>':message;
  const toggleWriting=enabled=>['save','new'].forEach(id=>$(id).disabled=!enabled);
  const render=()=>{$('entries').innerHTML=entries.length?entries.map((x,i)=>'<button class="book-spine" data-open="'+i+'"><small>'+escape(x.session_date||'Sans date')+'</small><b>'+escape(x.horse||'Ma séance')+'</b><small>'+escape(x.activity||'Journal équestre')+'</small></button>').join(''):'<p class="empty">Aucune page enregistrée pour le moment. Écris ta première séance dans ton livre.</p>';document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openEntry(Number(b.dataset.open)))};
  const openEntry=i=>{const x=entries[i];if(!x)return;currentEntry=x;$('deleteEntry').style.display='inline-block';$('entryTitle').textContent=x.horse||'Ma séance';$('entryMeta').innerHTML='<div>Date : '+escape(x.session_date||'—')+'</div><div>Séance : '+escape(x.activity||'—')+'</div><div>Humeur : '+escape(x.mood||'—')+'</div>';$('entryNotes').textContent=x.notes||'—';$('entryGoal').textContent=x.goal||'—';$('entryBook').classList.add('open');$('entryBook').scrollIntoView({behavior:'smooth'})};
  const blank=()=>{fields.forEach(f=>$(f).value='');$('date').valueAsDate=new Date();status('Nouvelle page prête.')};
  async function load(){const {data,error}=await db.from('journal_entries').select('*').order('session_date',{ascending:false}).order('created_at',{ascending:false});if(error){status('Le journal privé est en cours de préparation. Réessaie après la configuration Supabase.');return}entries=data||[];render()}
  $('save').onclick=async()=>{const notes=$('notes').value.trim();if(!notes){status('Écris quelques notes avant d’enregistrer.');return}const entry={user_id:user.id,session_date:$('date').value||null,horse:$('horse').value.trim()||null,activity:$('activity').value.trim()||null,mood:$('mood').value.trim()||null,notes,goal:$('goal').value.trim()||null};$('save').disabled=true;status('Enregistrement privé…');const {error}=await db.from('journal_entries').insert(entry);$('save').disabled=false;if(error){status('Impossible d’enregistrer pour le moment. Réessaie après la configuration Supabase.');return}status('Page enregistrée dans ton journal privé !',true);blank();await load()};
  $('new').onclick=blank;
  $('deleteEntry').onclick=async()=>{if(!currentEntry||!confirm('Supprimer définitivement cette séance ?'))return;$('deleteEntry').disabled=true;const {error}=await db.from('journal_entries').delete().eq('id',currentEntry.id);$('deleteEntry').disabled=false;if(error){status('Impossible de supprimer cette séance.');return}$('entryBook').classList.remove('open');$('deleteEntry').style.display='none';currentEntry=null;status('Séance supprimée.');await load()};
  $('backLibrary').onclick=()=>{$('entryBook').classList.remove('open');$('deleteEntry').style.display='none';$('entries').scrollIntoView({behavior:'smooth'})};
  (async()=>{const {data}=await db.auth.getUser();user=data.user;if(!user){toggleWriting(false);status('Connecte-toi avec ton espace membre pour ouvrir ton journal privé.');render();return}toggleWriting(true);status('Journal privé de ton compte : seul toi peux lire ces pages.',true);await load()})();
})();
