/* Generateur de noms personnalise et niveau de membre. */
(()=>{
  const en=()=>document.documentElement.lang==='en-US'||localStorage.getItem('dicochevalLocale')==='en-US';
  const t=(fr,english)=>en()?english:fr;
  const themes={
    elegant:'Cassiopée,Rubis,Saphir,Émeraude,Zéphir,Majesté,Sultan,Onyx,Topaze,Harmonie,Noblesse,Diamant,Velours,Ivoire,Opale',
    cute:'Flocon,Doudou,Waffle,Loulou,Mocha,Nougat,Vanille,Yuki,Poppy,Perle,Bambi,Cookie,Caprice,Jolie,Kiwi,Diabolo,Tempo,Câline,Choupette,Plume',
    sport:'Tonnerre,Legend,Champion,Éclair,Hurricane,Jazz,Lucky,Aventure,Légende,Thunder,Flash,Speedy,Storm,Victoire,Winner',
    magic:'Aurore,Céleste,Galaxie,Luna,Éclipse,Magic,Mystère,Pandora,Stella,Belle,Étoile,Mélodie,Fée,Nova,Célestia',
    colours:'Rose,Pink,Pinkie,Vanille,BlackBeauty,Blanche,Noire,Blondie,Goldie,Silver,Caramel,Blue,Red,Sunny'
  };
  const labels={elegant:['Élégant','Elegant'],cute:['Mignon','Cute'],sport:['Sportif','Sporty'],magic:['Féerique','Magical'],colours:['Couleurs','Colors']};
  const nav=()=>{const wrap=document.querySelector('.nav .wrap');if(wrap&&!wrap.querySelector('[href="#noms"]'))wrap.insertAdjacentHTML('beforeend','<a href="#noms">'+t('Noms','Names')+'</a><a href="journal.html">'+t('Journal','Journal')+'</a>')};
  const section=()=>{if(document.getElementById('noms'))return;const options=Object.keys(labels).map(k=>'<option value="'+k+'">'+t(...labels[k])+'</option>').join('');const letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('').map(x=>'<option value="'+x+'">'+x+'</option>').join('');const s=document.createElement('section');s.id='noms';s.className='section tint';s.innerHTML='<div class="wrap"><div class="head"><h2>'+t('Générateur de noms','Name generator')+'</h2><p>'+t('Choisis un style et, si tu veux, la première lettre du nom.','Choose a style and, if you want, the first letter.')+'</p></div><div class="name-tool"><label>'+t('Style','Style')+'<select id="nameTheme">'+options+'</select></label><label>'+t('Première lettre','First letter')+'<select id="nameLetter"><option value="">'+t('Toutes','Any letter')+'</option>'+letters+'</select></label><button class="btn" id="makeNames">'+t('Trouver des noms','Find names')+'</button></div><div class="name-results" id="nameResults" aria-live="polite"></div><button class="btn name-more" id="moreNames">'+t('Voir plus de noms','See more names')+'</button><a class="journal-link" href="journal.html">'+t('Ouvrir mon journal équestre →','Open my equestrian journal →')+'</a></div></section>';document.getElementById('quiz')?.before(s);let shown=12;const draw=()=>{const theme=document.getElementById('nameTheme').value,letter=document.getElementById('nameLetter').value;let pool=themes[theme].split(',');if(letter)pool=pool.filter(n=>n.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().startsWith(letter));document.getElementById('nameResults').innerHTML=pool.slice(0,shown).map(n=>'<span>'+n+'</span>').join('')||(t('Aucun nom dans ce style ne commence par cette lettre. Essaie une autre lettre ou un autre style.','No name in this style begins with that letter. Try another letter or style.'));document.getElementById('moreNames').style.display=pool.length>shown?'inline-block':'none'};document.getElementById('makeNames').onclick=()=>{shown=12;draw()};document.getElementById('moreNames').onclick=()=>{shown+=12;draw()};draw()};
  const level=()=>{const badges=JSON.parse(localStorage.getItem('dcBadges')||'[]');const points=Number(document.getElementById('memberPoints')?.textContent?.match(/\d+/)?.[0]||0);return 1+badges.length+Math.floor(points/10)};
  const showLevel=()=>{const holder=document.getElementById('memberPoints');if(!holder)return;let l=document.getElementById('memberLevel');if(!l){l=document.createElement('div');l.id='memberLevel';l.className='member-level';holder.after(l)}const b=JSON.parse(localStorage.getItem('dcBadges')||'[]').length,p=Math.floor(Number(holder.textContent.match(/\d+/)?.[0]||0)/10),n=level();l.innerHTML='<strong>'+ (en()?'Level ':'Niveau ') +n+'</strong><span>'+ (en()?b+' badge(s) · '+p+' ten-point step(s)':b+' badge(s) · '+p+' tranche(s) de 10 points.') +'</span>'};
  document.head.insertAdjacentHTML('beforeend','<style>.nav .wrap{display:flex!important;flex-wrap:wrap!important;justify-content:center!important;gap:3px!important;overflow:visible!important;padding:6px 12px!important}.nav a{font-size:12px!important;white-space:nowrap}.name-tool{display:flex;gap:12px;align-items:end;flex-wrap:wrap;background:#fffdf8;border:1px solid #d7e0d5;border-radius:16px;padding:20px}.name-tool label{display:grid;gap:6px;font-weight:800;color:#234238}.name-tool select{min-width:190px;padding:10px;border:1px solid #cbd8ce;border-radius:9px;font:inherit}.name-results{display:flex;flex-wrap:wrap;gap:10px;margin:18px 0}.name-results span{background:#e4eee7;color:#234238;border-radius:99px;padding:10px 15px;font-weight:800}.name-more{margin-bottom:18px}.journal-link{display:block;font-weight:800;color:#234238}.member-level{display:inline-flex;flex-direction:column;gap:2px;margin:13px 0 4px;padding:12px 16px;border-radius:13px;background:#234238;color:#fff;box-shadow:0 5px 13px #17352624}.member-level strong{font:700 29px/1 Georgia,serif;letter-spacing:.01em}.member-level span{font-size:11px;opacity:.88}@media(max-width:600px){.nav a{font-size:11px!important;padding:8px 9px!important}}</style>');
  setTimeout(()=>{nav();section();document.getElementById('topVisitorAccess')?.addEventListener('click',()=>setTimeout(showLevel,250));window.addEventListener('dc-badges-changed',showLevel);window.addEventListener('dc-points-changed',showLevel)},150);
})();
