/* Generateur de noms et niveau de membre. */
(()=>{
  const en=()=>document.documentElement.lang==='en-US'||localStorage.getItem('dicochevalLocale')==='en-US';
  const t=(fr,english)=>en()?english:fr;
  const themes={
    elegant:'Aramis,Arlequin,Athena,Balthazar,Byzance,Cassiopée,Céleste,Diabolo,Émeraude,Éole,Fandango,Galilée,Isadora,Jivago,Lancelot,Majesté,Orphée,Pegase,Roméo,Sultan,Toscane,Ulysse,Vivaldi,Zéphyr',
    sweet:'Bambi,Bijou,Câline,Choupette,Doudou,Flocon,Gaufrette,Loulou,Moka,Nouky,Paillette,Perle,Plume,Poppy,Praline,Réglisse,Toupie,Vanille,Whisky,Yuki',
    sport:'Action,Aiglon,Boléro,Champion,Diamant,Éclair,Fuego,Hurricane,Jackpot,Jazz,Komet,Legend,Mustang,Phenix,Rocket,Tornado,Viking,Voltige,Winner,Zeus',
    magic:'Aurore,Calypso,Célestia,Éclipse,Elfe,Fairy,Fée,Galaxie,Luna,Magic,Mystère,Narnia,Orion,Pandora,Saphir,Stella,Talisman,Théa,Trésor,Velvet',
    classic:'Albion,Alto,Amadeus,Apollon,Aristote,César,Charly,Dorian,Gatsby,Hector,Hugo,Iris,Jade,Lucky,Milady,Oscar,Prince,Queen,Royal,Soleil',
    colours:'Ambre,Blondie,Cannelle,Carbone,Cerise,Cobalt,Indigo,Noisette,Onyx,Opale,Orage,Perle,Rubis,Sable,Sépia,Silver,Topaze,Vanille,Velours,Violette',
    french:'Aventure,Belle,Caprice,Danseur,Étoile,Fidji,Gitane,Harmonie,Ibiza,Jolie,Kiwi,Légende,Melody,Noblesse,Océane,Passion,Quartz,Rêve,Symphonie,Tempo',
    rare:'Aster,Avalon,Boreal,Cirrus,Dexter,Eldorado,Gaïa,Hadès,Indiana,Junon,Kaïros,Loki,Maestro,Neroli,Oasis,Quasar,Raven,Saturne,Tango,Voltaire'
  };
  const labels={elegant:['Élégant','Elegant'],sweet:['Mignon','Cute'],sport:['Sportif','Sporty'],magic:['Féerique','Magical'],classic:['Classique','Classic'],colours:['Couleurs','Colors'],french:['Français','French'],rare:['Rare et original','Rare & original']};
  const nav=()=>{const wrap=document.querySelector('.nav .wrap');if(wrap&&!wrap.querySelector('[href="#noms"]'))wrap.insertAdjacentHTML('beforeend','<a href="#noms">'+t('Noms','Names')+'</a><a href="journal.html">'+t('Journal','Journal')+'</a>')};
  const section=()=>{if(document.getElementById('noms'))return;const options=Object.keys(labels).map(k=>'<option value="'+k+'">'+t(...labels[k])+'</option>').join('');const letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('').map(x=>'<option value="'+x+'">'+x+'</option>').join('');const s=document.createElement('section');s.id='noms';s.className='section tint';s.innerHTML='<div class="wrap"><div class="head"><h2>'+t('Générateur de noms','Name generator')+'</h2><p>'+t('Choisis un style et, si tu veux, la première lettre du nom.','Choose a style and, if you want, the first letter.')+'</p></div><div class="name-tool"><label>'+t('Style','Style')+'<select id="nameTheme">'+options+'</select></label><label>'+t('Première lettre','First letter')+'<select id="nameLetter"><option value="">'+t('Toutes','Any letter')+'</option>'+letters+'</select></label><button class="btn" id="makeNames">'+t('Trouver des noms','Find names')+'</button></div><div class="name-results" id="nameResults" aria-live="polite"></div><button class="btn name-more" id="moreNames">'+t('Voir plus de noms','See more names')+'</button><a class="journal-link" href="journal.html">'+t('Ouvrir mon journal équestre →','Open my equestrian journal →')+'</a></div></section>';document.getElementById('quiz')?.before(s);let shown=12;const draw=()=>{const theme=document.getElementById('nameTheme').value,letter=document.getElementById('nameLetter').value;let pool=themes[theme].split(',');if(letter)pool=pool.filter(n=>n.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().startsWith(letter));document.getElementById('nameResults').innerHTML=pool.slice(0,shown).map(n=>'<span>'+n+'</span>').join('')||(t('Aucun nom dans ce thème ne commence par cette lettre. Essaie une autre lettre ou un autre thème.','No name in this style begins with that letter. Try another letter or style.'));document.getElementById('moreNames').style.display=pool.length>shown?'inline-block':'none'};document.getElementById('makeNames').onclick=()=>{shown=12;draw()};document.getElementById('moreNames').onclick=()=>{shown+=12;draw()};draw()};
  const level=()=>{const badges=JSON.parse(localStorage.getItem('dcBadges')||'[]');const points=Number(document.getElementById('memberPoints')?.textContent?.match(/\d+/)?.[0]||0);return 1+badges.length+Math.floor(points/10)};
  const showLevel=()=>{const holder=document.getElementById('memberPoints');if(!holder)return;let l=document.getElementById('memberLevel');if(!l){l=document.createElement('p');l.id='memberLevel';l.className='member-status';holder.after(l)}const b=JSON.parse(localStorage.getItem('dcBadges')||'[]').length,p=Math.floor(Number(holder.textContent.match(/\d+/)?.[0]||0)/10);l.textContent=en()?'Level '+level()+' · '+b+' badge(s) · '+p+' ten-point step(s).':'Niveau '+level()+' · '+b+' badge(s) · '+p+' tranche(s) de 10 points.'};
  document.head.insertAdjacentHTML('beforeend','<style>.name-tool{display:flex;gap:12px;align-items:end;flex-wrap:wrap;background:#fffdf8;border:1px solid #d7e0d5;border-radius:16px;padding:20px}.name-tool label{display:grid;gap:6px;font-weight:800;color:#234238}.name-tool select{min-width:190px;padding:10px;border:1px solid #cbd8ce;border-radius:9px;font:inherit}.name-results{display:flex;flex-wrap:wrap;gap:10px;margin:18px 0}.name-results span{background:#e4eee7;color:#234238;border-radius:99px;padding:10px 15px;font-weight:800}.name-more{margin-bottom:18px}.journal-link{display:block;font-weight:800;color:#234238}</style>');
  setTimeout(()=>{nav();section();document.getElementById('topVisitorAccess')?.addEventListener('click',()=>setTimeout(showLevel,250));window.addEventListener('dc-badges-changed',showLevel);window.addEventListener('dc-points-changed',showLevel)},150);
})();
