/* Générateur de noms et niveau de membre. */
(()=>{
  const en=()=>document.documentElement.lang==='en-US'||localStorage.getItem('dicochevalLocale')==='en-US';
  const t=(fr,english)=>en()?english:fr;
  const names={calm:['Sérénité','Nuage','Éden','Lune','Brise','Velours','Harmonie','Mistral'],cute:['Pompon','Cookie','Nougat','Praline','Caramel','Pistache','Muffin','Biscuit'],nature:['Forêt','Sauge','Orage','Rivière','Étoile','Soleil','Aurore','Sirocco'],strong:['Titan','Valkyrie','Atlas','Nova','Olympe','Tempête','Ragnar','Héra'],western:['Dakota','Cheyenne','Rio','Sierra','Canyon','Apache','Rodeo','Mojave'],elegant:['Opale','Saphir','Astre','Jasmin','Éclipse','Velvet','Ambre','Noble']};
  const englishNames={calm:['Serenity','Cloud','Eden','Moon','Breeze','Velvet','Harmony','Mistral'],cute:['Pompom','Cookie','Nougat','Praline','Caramel','Pistachio','Muffin','Biscuit'],nature:['Forest','Sage','Storm','River','Star','Sunny','Dawn','Sirocco'],strong:['Titan','Valkyrie','Atlas','Nova','Olympus','Storm','Ragnar','Hera'],western:['Dakota','Cheyenne','Rio','Sierra','Canyon','Apache','Rodeo','Mojave'],elegant:['Opal','Sapphire','Aster','Jasmine','Eclipse','Velvet','Amber','Noble']};
  const nav=()=>{const wrap=document.querySelector('.nav .wrap');if(wrap&&!wrap.querySelector('[href="#noms"]'))wrap.insertAdjacentHTML('beforeend','<a href="#noms">'+t('Noms','Names')+'</a><a href="journal.html">'+t('Journal','Journal')+'</a>')};
  const section=()=>{if(document.getElementById('noms'))return;const s=document.createElement('section');s.id='noms';s.className='section tint';s.innerHTML='<div class="wrap"><div class="head"><h2>'+t('Générateur de noms','Name generator')+'</h2><p>'+t('Choisis un thème pour trouver de jolies idées pour ton cheval ou ton poney.','Choose a theme to find lovely ideas for your horse or pony.')+'</p></div><div class="name-tool"><label>'+t('Thème','Theme')+'<select id="nameTheme"><option value="calm">'+t('Calme','Calm')+'</option><option value="cute">'+t('Mignon','Cute')+'</option><option value="nature">'+t('Nature','Nature')+'</option><option value="strong">'+t('Puissant','Strong')+'</option><option value="western">Western</option><option value="elegant">'+t('Élégant','Elegant')+'</option></select></label><button class="btn" id="makeNames">'+t('Trouver des noms','Find names')+'</button></div><div class="name-results" id="nameResults" aria-live="polite"></div><a class="journal-link" href="journal.html">'+t('Ouvrir mon journal équestre →','Open my equestrian journal →')+'</a></div></section>';document.getElementById('quiz')?.before(s);const draw=()=>{const theme=document.getElementById('nameTheme').value,pool=(en()?englishNames:names)[theme];document.getElementById('nameResults').innerHTML=pool.sort(()=>Math.random()-.5).slice(0,6).map(n=>'<span>'+n+'</span>').join('')};document.getElementById('makeNames').onclick=draw;draw()};
  const level=()=>{const badges=JSON.parse(localStorage.getItem('dcBadges')||'[]');const points=Number(document.getElementById('memberPoints')?.textContent?.match(/\d+/)?.[0]||0);return 1+badges.length+Math.floor(points/10)};
  const showLevel=()=>{const holder=document.getElementById('memberPoints');if(!holder)return;let l=document.getElementById('memberLevel');if(!l){l=document.createElement('p');l.id='memberLevel';l.className='member-status';holder.after(l)}const b=JSON.parse(localStorage.getItem('dcBadges')||'[]').length,p=Math.floor(Number(holder.textContent.match(/\d+/)?.[0]||0)/10);l.textContent=en()?'Level '+level()+' · '+b+' badge(s) · '+p+' ten-point step(s).':'Niveau '+level()+' · '+b+' badge(s) · '+p+' tranche(s) de 10 points.'};
  document.head.insertAdjacentHTML('beforeend','<style>.name-tool{display:flex;gap:12px;align-items:end;flex-wrap:wrap;background:#fffdf8;border:1px solid #d7e0d5;border-radius:16px;padding:20px}.name-tool label{display:grid;gap:6px;font-weight:800;color:#234238}.name-tool select{min-width:190px;padding:10px;border:1px solid #cbd8ce;border-radius:9px;font:inherit}.name-results{display:flex;flex-wrap:wrap;gap:10px;margin:18px 0}.name-results span{background:#e4eee7;color:#234238;border-radius:99px;padding:10px 15px;font-weight:800}.journal-link{font-weight:800;color:#234238}</style>');
  setTimeout(()=>{nav();section();document.getElementById('topVisitorAccess')?.addEventListener('click',()=>setTimeout(showLevel,250));window.addEventListener('dc-badges-changed',showLevel);window.addEventListener('dc-points-changed',showLevel)},150);
})();
