/* Espace membre : profil visiteur et photo personnelle. */
(() => {
  const db = window.supabase.createClient('https://mmxdlnfntpufwwkdvgzc.supabase.co','sb_publishable_Pa-DX3nwNTZktbWK46KDQg_IuIy8TZP');
  const button = document.getElementById('topVisitorAccess');
  if (!button) return;
  document.head.insertAdjacentHTML('beforeend','<style>.member-modal{position:fixed;inset:0;background:#173526bb;z-index:140;display:none;align-items:center;justify-content:center;padding:20px}.member-modal.open{display:flex}.member-box{position:relative;width:min(500px,100%);background:#fffdf8;border-radius:15px;padding:28px}.member-box h2{color:#234238;margin-top:0}.member-close{position:absolute;right:13px;top:10px;background:none!important;color:#234238!important;font-size:24px}.member-avatar{width:88px;height:88px;border-radius:50%;object-fit:cover;background:#dfe9df;border:2px solid #b58a4b;display:block;margin:8px 0 14px}.member-box input{width:100%;padding:10px;margin:5px 0 12px;border:1px solid #cbd8ce;border-radius:6px;font:14px Arial}.member-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:8px}.member-status{font-size:13px;color:#50685d;min-height:18px}</style>');
  document.body.insertAdjacentHTML('beforeend','<div class="member-modal" id="memberModal"><div class="member-box"><button class="member-close" id="memberClose">×</button><h2>Mon espace membre</h2><p id="memberEmail" class="member-status"></p><img id="memberAvatar" class="member-avatar" alt="Photo de profil"><label for="memberPseudo">Pseudo</label><input id="memberPseudo" maxlength="40" placeholder="Choisis ton pseudo"><label for="memberAvatarFile">Photo de profil (facultatif)</label><input id="memberAvatarFile" type="file" accept="image/png,image/jpeg,image/webp"><p id="memberStatus" class="member-status"></p><div class="member-actions"><button class="btn" id="saveMemberProfile">Enregistrer mon profil</button><button class="btn danger" id="memberSignOut">Se déconnecter</button></div></div></div>');
  const $ = id => document.getElementById(id);
  const modal = $('memberModal');
  let currentUser = null, pendingPreview = '';
  const reservedName = value => String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'').includes('dicocheval');
  const fallback = 'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="96" height="96"><rect width="100%" height="100%" fill="#dfe9df"/><text x="50%" y="58%" text-anchor="middle" font-family="Arial" font-size="42" fill="#234238">?</text></svg>');
  async function refreshButton(){const {data}=await db.auth.getUser();button.textContent=data.user?'Mon espace membre':'Se connecter visiteur'}
  function showProfile(user){currentUser=user;const profile=user.user_metadata||{};$('memberEmail').textContent='Connecté·e : '+(user.email||'');$('memberPseudo').value=profile.pseudo||'';$('memberAvatar').src=profile.avatar_url||fallback;$('memberAvatarFile').value='';$('memberStatus').textContent='';pendingPreview='';modal.classList.add('open')}
  async function openProfile(){const {data}=await db.auth.getUser();if(!data.user){$('commentAuthModal')?.classList.add('open');return}showProfile(data.user)}
  button.onclick=openProfile;
  $('memberClose').onclick=()=>modal.classList.remove('open');
  $('memberAvatarFile').onchange=()=>{const file=$('memberAvatarFile').files[0];if(!file)return;if(file.size>3*1024*1024){$('memberStatus').textContent='Choisis une image de 3 Mo maximum.';$('memberAvatarFile').value='';return}pendingPreview=URL.createObjectURL(file);$('memberAvatar').src=pendingPreview;$('memberStatus').textContent='Photo choisie : clique sur Enregistrer mon profil.'};
  $('saveMemberProfile').onclick=async()=>{if(!currentUser)return;const pseudo=$('memberPseudo').value.trim();const file=$('memberAvatarFile').files[0];if(reservedName(pseudo)&&currentUser.id!=='f22161e4-7528-4fd2-9860-a18be084b1f6'){$('memberStatus').textContent='Ce pseudo ne peut pas être utilisé.';return}$('memberStatus').textContent='Enregistrement…';let avatarUrl=currentUser.user_metadata?.avatar_url||'';if(file){const ext=(file.name.split('.').pop()||'jpg').toLowerCase(),path=currentUser.id+'/avatar-'+Date.now()+'.'+ext;const {error:uploadError}=await db.storage.from('avatars').upload(path,file,{upsert:true,contentType:file.type});if(uploadError){$('memberStatus').textContent='La photo ne peut pas encore être enregistrée. Il faut activer le dossier Images dans Supabase.';return}avatarUrl=db.storage.from('avatars').getPublicUrl(path).data.publicUrl}const {data,error}=await db.auth.updateUser({data:{pseudo,avatar_url:avatarUrl}});if(error){$('memberStatus').textContent='Le profil n’a pas pu être enregistré.';return}currentUser=data.user||currentUser;$('memberStatus').textContent='Profil enregistré !';$('memberAvatar').src=avatarUrl||fallback;refreshButton()};
  $('memberSignOut').onclick=async()=>{await db.auth.signOut();modal.classList.remove('open');refreshButton()};
  db.auth.onAuthStateChange(()=>setTimeout(refreshButton,0));
  refreshButton();
})();