(() => {
  const $=id=>document.getElementById(id);
  const profiles=[
    {name:'Labrador Retriever',size:'large',activity:'high',time:90,experience:'beginner',children:true,groom:'medium',style:'family',homes:['house','land','apartment']},
    {name:'Golden Retriever',size:'large',activity:'high',time:90,experience:'beginner',children:true,groom:'high',style:'family',homes:['house','land']},
    {name:'Caniche standard',size:'large',activity:'high',time:90,experience:'some',children:true,groom:'high',style:'sport',homes:['house','land','apartment']},
    {name:'Cavalier King Charles Spaniel',size:'small',activity:'low',time:45,experience:'beginner',children:true,groom:'medium',style:'family',homes:['apartment','house']},
    {name:'Shih Tzu',size:'small',activity:'low',time:45,experience:'beginner',children:true,groom:'high',style:'family',homes:['apartment','house']},
    {name:'Beagle',size:'medium',activity:'high',time:90,experience:'some',children:true,groom:'low',style:'sport',homes:['house','land']},
    {name:'Border Collie',size:'medium',activity:'high',time:150,experience:'advanced',children:false,groom:'medium',style:'sport',homes:['land']},
    {name:'Berger australien',size:'medium',activity:'high',time:150,experience:'some',children:true,groom:'medium',style:'sport',homes:['house','land']},
    {name:'Eurasier',size:'large',activity:'medium',time:90,experience:'some',children:true,groom:'high',style:'family',homes:['house','land']},
    {name:'Basenji',size:'medium',activity:'high',time:90,experience:'advanced',children:false,groom:'low',style:'independent',homes:['house','apartment']},
    {name:'Chihuahua',size:'small',activity:'low',time:45,experience:'some',children:false,groom:'low',style:'family',homes:['apartment','house']},
    {name:'Chien finnois de Laponie',size:'medium',activity:'high',time:90,experience:'some',children:true,groom:'high',style:'family',homes:['house','land']},
    {name:'Lagotto Romagnolo',size:'medium',activity:'high',time:90,experience:'some',children:true,groom:'high',style:'sport',homes:['house','land']},
    {name:'Terrier tchèque',size:'small',activity:'medium',time:60,experience:'some',children:true,groom:'medium',style:'family',homes:['apartment','house']},
    {name:'Terre-Neuve',size:'large',activity:'medium',time:90,experience:'some',children:true,groom:'high',style:'family',homes:['house','land']}
  ];
  const activityRank={low:1,medium:2,high:3},experienceRank={beginner:1,some:2,advanced:3},groomRank={low:1,medium:2,high:3};
  $('idealSubmit').onclick=()=>{const values={home:$('idealHome').value,activity:$('idealActivity').value,time:Number($('idealTime').value),experience:$('idealExperience').value,children:$('idealChildren').value,size:$('idealSize').value,groom:$('idealGroom').value,style:$('idealStyle').value};if(Object.values(values).some(v=>v===''||v===0)){$('idealResult').className='result open';$('idealResult').textContent='Tu n’as pas rempli toutes les informations.';return}const scored=profiles.map(p=>{let score=0,reasons=[];if(p.homes.includes(values.home)){score+=3;reasons.push('logement compatible')}if(values.size==='any'||p.size===values.size){score+=3;reasons.push('format recherché')}const activityGap=Math.abs(activityRank[p.activity]-activityRank[values.activity]);score+=Math.max(0,3-activityGap*2);if(p.time<=values.time){score+=3;reasons.push('temps quotidien adapté')}if(experienceRank[p.experience]<=experienceRank[values.experience])score+=2;if(values.children==='no'||p.children){score+=2;if(values.children==='yes')reasons.push('profil familial')}if(groomRank[p.groom]<=groomRank[values.groom])score+=2;if(p.style===values.style){score+=3;reasons.push('tempérament recherché')}return {...p,score,reasons}}).sort((a,b)=>b.score-a.score).slice(0,3);$('idealResult').className='result open';$('idealResult').innerHTML='<h3>Les trois profils les plus compatibles</h3><div class="recommendations">'+scored.map((p,i)=>'<article class="recommendation"><small>Compatibilité '+Math.round(p.score/21*100)+' %</small><h3>'+p.name+'</h3><p>'+p.reasons.join(' · ')+'</p><a href="dicochien.html?breed='+encodeURIComponent(p.name)+'">Voir sa fiche →</a></article>').join('')+'</div><p><small>Ce résultat aide à réfléchir, mais chaque chien est un individu. Rencontre-le et discute avec un refuge ou un professionnel avant toute décision.</small></p>'};
  $('budgetSubmit').onclick=()=>{const size=$('budgetSize').value,coat=$('budgetCoat').value,activity=$('budgetActivity').value,breed=$('budgetBreed').value;const breedFactor={standard:1,labrador:1.08,golden:1.12,poodle:1.16,bulldog:1.22,beagle:1,border:1.08,husky:1.12,chihuahua:.9,newfoundland:1.3}[breed];const breedName=$('budgetBreed').selectedOptions[0].textContent;const food=Math.round(({small:650,medium:950,large:1350,giant:1900}[size]+(activity==='high'?180:activity==='very-high'?350:0))*breedFactor),vet=Math.round({small:650,medium:700,large:780,giant:900}[size]*breedFactor),groom=Math.round({easy:180,regular:420,pro:950}[coat]*breedFactor),insurance=Math.round({small:550,medium:680,large:820,giant:1050}[size]*breedFactor),gear={small:320,medium:420,large:520,giant:650}[size],training=350,total=food+vet+groom+insurance+gear+training,low=Math.round(total*.85),high=Math.round(total*1.25);$('budgetResult').className='result open';$('budgetResult').innerHTML='<h3>'+breedName+'</h3><div class="budget-total">'+low.toLocaleString('fr-CA')+' à '+high.toLocaleString('fr-CA')+' $ / an</div><div class="budget-lines"><span>Alimentation : ≈ '+food+' $</span><span>Prévention vétérinaire : ≈ '+vet+' $</span><span>Toilettage : ≈ '+groom+' $</span><span>Assurance : ≈ '+insurance+' $</span><span>Matériel : ≈ '+gear+' $</span><span>Éducation : ≈ '+training+' $</span></div><p><small>La race ajuste l’estimation pour les besoins moyens connus, mais chaque chien est différent. Prévois aussi un fonds d’urgence séparé. Les prix varient selon la région, la santé et les services choisis.</small></p>'};
  const questions=[
    ['Que doit toujours avoir un chien ?',['De l’eau fraîche','Du lait','Du jus'],'De l’eau fraîche'],['Quel professionnel diagnostique une maladie ?',['Le vétérinaire','Le toiletteur','Le promeneur'],'Le vétérinaire'],['Un chien qui se fige peut être…',['Inconfortable','Toujours joyeux','Endormi debout'],'Inconfortable'],['Le rappel se travaille d’abord…',['Dans un lieu calme','Au bord d’une route','Sans récompense'],'Dans un lieu calme'],['Avant de changer de nourriture…',['Faire une transition progressive','Tout changer immédiatement','Faire jeûner trois jours'],'Faire une transition progressive'],['Le chocolat est…',['Toxique pour le chien','Un bon prix','Recommandé après le sport'],'Toxique pour le chien'],['Une laisse détendue se récompense…',['Rapidement','Une semaine plus tard','Jamais'],'Rapidement'],['Les griffes trop longues peuvent…',['Gêner les déplacements','Améliorer la course','Nettoyer les sols'],'Gêner les déplacements'],['Par forte chaleur, il faut…',['Réduire l’effort','Courir à midi','Laisser le chien en voiture'],'Réduire l’effort'],['La socialisation doit être…',['Progressive et positive','Forcée','Punitive'],'Progressive et positive'],['Un changement soudain de comportement mérite…',['Une vérification vétérinaire','D’être ignoré','Une punition'],'Une vérification vétérinaire'],['Le flair est une activité…',['Mentalement stimulante','Inutile','Réservée aux chiots'],'Mentalement stimulante'],['Le poids idéal se surveille avec…',['La silhouette et le vétérinaire','La couleur du collier','La longueur de la queue'],'La silhouette et le vétérinaire'],['Un chien qui revient au rappel doit être…',['Récompensé','Puni pour le délai','Ignoré'],'Récompensé'],['Avant une adoption, il faut considérer…',['Temps, budget et besoins','Seulement la couleur','Seulement le nom'],'Temps, budget et besoins']
  ];let qi=0,score=0,locked=false;
  function drawQuiz(){if(qi>=questions.length){finishQuiz();return}locked=false;const q=questions[qi];$('quizProgress').textContent='Question '+(qi+1)+' / '+questions.length;$('quizQuestion').textContent=q[0];$('quizAnswers').innerHTML=q[1].map(a=>'<button>'+a+'</button>').join('');$('quizFeedback').textContent='';$('quizAnswers').querySelectorAll('button').forEach(b=>b.onclick=()=>answerQuiz(b.textContent));}
  function answerQuiz(answer){if(locked)return;locked=true;const good=answer===questions[qi][2];if(good)score++;$('quizFeedback').textContent=good?'Bravo, bonne réponse !':'Bonne réponse : '+questions[qi][2];setTimeout(()=>{qi++;drawQuiz()},1100)}
  async function finishQuiz(){const percent=Math.round(score/questions.length*100);$('quizProgress').textContent='Quiz terminé';$('quizQuestion').textContent=score+' / '+questions.length+' — '+percent+' %';$('quizAnswers').innerHTML='';$('quizFeedback').textContent=percent>=80?'Badge « Expert canin » débloqué !':'Recommence pour atteindre 80 % et débloquer le badge.';$('quizRestart').hidden=false;if(percent>=80){const badges=JSON.parse(localStorage.getItem('dcBadges')||'[]');if(!badges.includes('Expert canin')){badges.push('Expert canin');localStorage.setItem('dcBadges',JSON.stringify(badges));window.dispatchEvent(new Event('dc-badges-changed'))}try{const db=window.supabase.createClient('https://mmxdlnfntpufwwkdvgzc.supabase.co','sb_publishable_Pa-DX3nwNTZktbWK46KDQg_IuIy8TZP'),{data}=await db.auth.getUser();if(data.user){const list=Array.isArray(data.user.user_metadata?.dog_badges)?data.user.user_metadata.dog_badges:[];if(!list.includes('Expert canin'))await db.auth.updateUser({data:{dog_badges:[...list,'Expert canin'],dog_quiz_best:Math.max(percent,Number(data.user.user_metadata?.dog_quiz_best||0))}})}}catch(_){}}}
  $('quizRestart').onclick=()=>{qi=0;score=0;$('quizRestart').hidden=true;drawQuiz()};drawQuiz();
  const names={cute:'Mochi,Nougat,Waffle,Loulou,Poppy,Bambi,Cookie,Yuki,Vanille,Mocha,Flocon,Doudou,Kiwi,Tempo,Diabolo,Perle',elegant:'Cassiopée,Rubis,Saphir,Émeraude,Zéphir,Majesté,Sultan,Onyx,Topaze,Harmonie,Noblesse,Velours,Opale',sport:'Tonnerre,Legend,Champion,Éclair,Hurricane,Jazz,Lucky,Aventure,Légende,Dash,Flash,Rocket,Storm,Volt',nature:'Willow,Maple,Cèdre,Forêt,Océan,Neige,Brume,Soleil,Lune,Rivage,Orage,Meadow,Flora',magic:'Aurore,Céleste,Galaxie,Luna,Eclipse,Magic,Mystère,Pandora,Stella,Belle,Étoile,Mélodie,Comète',food:'Muffin,Biscuit,Caramel,Cannelle,Praline,Pistache,Churro,Peanut,Taco,Brownie,Toffee,Olive,Truffe'};
  'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('').forEach(l=>$('nameLetter').insertAdjacentHTML('beforeend','<option>'+l+'</option>'));
  function makeNames(){const letter=$('nameLetter').value;let pool=names[$('nameTheme').value].split(',');if(letter)pool=pool.filter(n=>n.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().startsWith(letter));$('nameResults').innerHTML=(pool.length?pool:['Aucun nom pour cette lettre']).map(n=>'<span>'+n+'</span>').join('')}$('nameGenerate').onclick=makeNames;makeNames();
})();
