(()=>{'use strict';
const $=id=>document.getElementById(id),language=$('language');
let en=(localStorage.getItem('dicopetsLanguage')||'fr')==='en';
const route=new URLSearchParams(location.search).get('outil')||location.hash.slice(1)||'ideal';
document.querySelectorAll('.tool-section').forEach(s=>s.classList.toggle('active',s.id===route));

const cats=[
{n:'Abyssin',home:'house',presence:'high',time:90,energy:'high',style:'playful',coat:'short',groom:'low',kids:'yes',pets:'yes',summary:['Explorateur agile, curieux et très joueur.','Agile, curious and highly playful explorer.'],watch:['Il tolère mal l’ennui et les longues journées sans interaction.','It may struggle with boredom and long days without interaction.']},
{n:'Bengal',home:'house',presence:'high',time:90,energy:'high',style:'playful',coat:'short',groom:'low',kids:'yes',pets:'yes',summary:['Athlétique et intelligent, il demande beaucoup d’enrichissement.','Athletic and intelligent, it needs extensive enrichment.'],watch:['Une personne très disponible et expérimentée est préférable.','A very available, experienced owner is preferable.']},
{n:'Bleu russe',home:'small',presence:'medium',time:30,energy:'medium',style:'independent',coat:'short',groom:'low',kids:'no',pets:'no',summary:['Calme, fidèle et sensible aux routines stables.','Calm, loyal and sensitive to stable routines.'],watch:['Les changements brusques et le bruit peuvent le stresser.','Sudden changes and noise may cause stress.']},
{n:'Bombay',home:'apartment',presence:'high',time:60,energy:'medium',style:'cuddly',coat:'short',groom:'low',kids:'yes',pets:'yes',summary:['Sociable, affectueux et généralement joueur.','Social, affectionate and generally playful.'],watch:['Il apprécie peu les longues périodes de solitude.','It dislikes long periods alone.']},
{n:'British Shorthair',home:'small',presence:'low',time:30,energy:'low',style:'calm',coat:'short',groom:'low',kids:'yes',pets:'yes',summary:['Paisible, stable et assez indépendant.','Peaceful, steady and fairly independent.'],watch:['Il faut surveiller son poids et respecter son besoin de tranquillité.','Weight should be monitored and its need for quiet respected.']},
{n:'Chartreux',home:'apartment',presence:'medium',time:30,energy:'medium',style:'calm',coat:'short',groom:'low',kids:'yes',pets:'yes',summary:['Observateur, loyal et discret.','Observant, loyal and discreet.'],watch:['Sa discrétion peut masquer une douleur ou un inconfort.','Its quiet nature can hide pain or discomfort.']},
{n:'Cornish Rex',home:'small',presence:'high',time:90,energy:'high',style:'playful',coat:'curly',groom:'medium',kids:'yes',pets:'yes',summary:['Très actif, chaleureux et proche de l’humain.','Very active, warm-seeking and people-oriented.'],watch:['Il est sensible au froid et demande beaucoup d’activité.','It is sensitive to cold and needs plenty of activity.']},
{n:'Devon Rex',home:'small',presence:'high',time:60,energy:'high',style:'playful',coat:'curly',groom:'medium',kids:'yes',pets:'yes',summary:['Espiègle, câlin et très sociable.','Mischievous, cuddly and highly social.'],watch:['Sa peau et ses oreilles demandent un entretien régulier.','Its skin and ears need regular care.']},
{n:'Maine Coon',home:'house',presence:'medium',time:60,energy:'medium',style:'cuddly',coat:'long',groom:'high',kids:'yes',pets:'yes',summary:['Grand chat doux, sociable et joueur.','Large, gentle, social and playful cat.'],watch:['Il exige du matériel robuste, du brossage et un suivi cardiaque attentif.','It needs sturdy equipment, brushing and attentive heart screening.']},
{n:'Norvégien',home:'house',presence:'medium',time:60,energy:'high',style:'independent',coat:'long',groom:'high',kids:'yes',pets:'yes',summary:['Grimpeur robuste, agile et équilibré.','Hardy, agile and balanced climber.'],watch:['Il a besoin de hauteur et d’un brossage accru pendant la mue.','It needs climbing space and extra brushing while shedding.']},
{n:'Persan',home:'small',presence:'medium',time:30,energy:'low',style:'calm',coat:'long',groom:'high',kids:'no',pets:'yes',summary:['Tranquille, tendre et adapté à un foyer paisible.','Quiet, tender and suited to a peaceful home.'],watch:['Brossage quotidien, soins des yeux et vigilance respiratoire sont essentiels.','Daily brushing, eye care and respiratory monitoring are essential.']},
{n:'Ragdoll',home:'apartment',presence:'high',time:60,energy:'low',style:'cuddly',coat:'long',groom:'high',kids:'yes',pets:'yes',summary:['Doux, détendu et très proche de ses humains.','Gentle, relaxed and very people-oriented.'],watch:['Il supporte mal les longues absences et doit vivre dans un milieu sécurisé.','It struggles with long absences and needs a secure environment.']},
{n:'Sacré de Birmanie',home:'apartment',presence:'high',time:60,energy:'low',style:'cuddly',coat:'long',groom:'medium',kids:'yes',pets:'yes',summary:['Équilibré, patient et affectueux.','Balanced, patient and affectionate.'],watch:['Il demande une présence affective régulière.','It needs regular affectionate company.']},
{n:'Siamois',home:'apartment',presence:'high',time:90,energy:'high',style:'cuddly',coat:'short',groom:'low',kids:'yes',pets:'yes',summary:['Communicatif, intelligent et très attaché à son foyer.','Communicative, intelligent and strongly attached to its home.'],watch:['Il peut être très vocal et vivre difficilement la solitude.','It can be very vocal and may struggle with loneliness.']},
{n:'Sibérien',home:'house',presence:'medium',time:60,energy:'high',style:'playful',coat:'long',groom:'high',kids:'yes',pets:'yes',summary:['Puissant, joueur et généralement sociable.','Powerful, playful and generally social.'],watch:['Aucune race n’est véritablement hypoallergénique.','No cat breed is truly hypoallergenic.']},
{n:'Sphynx',home:'apartment',presence:'high',time:60,energy:'high',style:'cuddly',coat:'none',groom:'high',kids:'yes',pets:'yes',summary:['Très sociable, chaleureux et proche de l’humain.','Highly social, warm-seeking and people-oriented.'],watch:['Peau, oreilles et température exigent des soins particuliers.','Skin, ears and body temperature require special care.']}
];
const answerIds=['iHome','iPresence','iTime','iEnergy','iStyle','iCoat','iGroom','iKids','iPets'];
const closeness=(a,b,order)=>Math.abs(order.indexOf(a)-order.indexOf(b));
function scoreCat(c,v){let score=0,max=0,reasons=[];const exact=(key,weight,labelFr,labelEn)=>{max+=weight;if(c[key]===v[key]){score+=weight;reasons.push(en?labelEn:labelFr)}};
  max+=18;const homeOrder=['small','apartment','house'],hd=closeness(c.home,v.home,homeOrder);score+=hd===0?18:hd===1?11:4;if(hd===0)reasons.push(en?'home type fits':'logement adapté');
  exact('presence',15,'présence compatible','compatible presence');
  max+=14;const timeGap=Math.abs(c.time-Number(v.time));score+=timeGap===0?14:timeGap<=30?9:3;if(timeGap===0)reasons.push(en?'daily time fits':'temps quotidien adapté');
  max+=15;const energyOrder=['low','medium','high'],ed=closeness(c.energy,v.energy,energyOrder);score+=ed===0?15:ed===1?8:1;if(ed===0)reasons.push(en?'matching energy':'énergie correspondante');
  exact('style',13,'relation recherchée','preferred bond');
  max+=10;if(v.coat==='any'){score+=8}else if(c.coat===v.coat){score+=10;reasons.push(en?'preferred coat':'pelage souhaité')}
  max+=8;const groomOrder=['low','medium','high'],gd=closeness(c.groom,v.groom,groomOrder);score+=gd===0?8:gd===1?4:0;
  exact('kids',4,'compatible avec les enfants','compatible with children');exact('pets',3,'cohabitation possible','possible with other pets');
  return{...c,percent:Math.max(38,Math.round(score/max*100)),reasons};
}
$('findIdeal').onclick=()=>{const v=Object.fromEntries(answerIds.map(id=>[id.slice(1).toLowerCase(),$(id).value]));v.time=$('iTime').value;v.style=$('iStyle').value;v.coat=$('iCoat').value;if(answerIds.some(id=>!$(id).value)){$('idealResult').innerHTML=`<p class="error">${en?'You have not completed every field.':'Tu n’as pas rempli toutes les informations.'}</p>`;return}const r=cats.map(c=>scoreCat(c,v)).sort((a,b)=>b.percent-a.percent||a.n.localeCompare(b.n)).slice(0,4);$('idealResult').innerHTML=r.map(x=>`<article class="card ideal-card"><h3>${x.n}</h3><div class="match">${x.percent} %</div><p>${x.summary[en?1:0]}</p><p class="why"><strong>${en?'Why it fits:':'Pourquoi :'} </strong>${x.reasons.slice(0,4).join(' · ')|| (en?'balanced overall profile':'profil global équilibré')}</p><p><strong>${en?'Ideal home:':'Foyer idéal :'} </strong>${homeText(x)}</p><p><strong>${en?'Daily time:':'Temps quotidien :'} </strong>${x.time} min</p><p><strong>${en?'Grooming:':'Entretien :'} </strong>${groomText(x.groom)}</p><p><strong>${en?'Watch for:':'À surveiller :'} </strong>${x.watch[en?1:0]}</p></article>`).join('')};
function homeText(c){const t={small:['petit appartement enrichi','enriched small apartment'],apartment:['appartement enrichi ou maison','enriched apartment or house'],house:['maison ou grand logement très enrichi','house or a large, highly enriched home']};return t[c.home][en?1:0]}
function groomText(v){return({low:['léger','light'],medium:['régulier','regular'],high:['fréquent à quotidien','frequent to daily']}[v][en?1:0])}

const breedFactors={'Chat domestique / croisé':1,'Abyssin':1,'Bengal':1.08,'Bleu russe':1,'Bombay':1,'British Shorthair':1.05,'Chartreux':1.03,'Cornish Rex':1.05,'Devon Rex':1.05,'Maine Coon':1.2,'Norvégien':1.17,'Persan':1.13,'Ragdoll':1.12,'Sacré de Birmanie':1.08,'Siamois':1,'Sibérien':1.16,'Sphynx':1.16};
function fillBreeds(){const previous=$('bBreed').value;$('bBreed').innerHTML=`<option value="">${en?'Choose…':'Choisir…'}</option>`+Object.keys(breedFactors).sort((a,b)=>a.localeCompare(b,en?'en':'fr')).map(n=>`<option value="${n}">${en&&n==='Chat domestique / croisé'?'Domestic or mixed-breed cat':n}</option>`).join('');$('bBreed').value=previous}
const ranges={food:{standard:[420,720],premium:[720,1200],veterinary:[1200,2000]},age:{kitten:[450,900],adult:[250,550],senior:[500,1200]},groom:{home:[60,160],basic:[200,450],professional:[500,1000]},insurance:{none:[0,0],basic:[300,650],complete:[650,1200]}};
$('calcBudget').onclick=()=>{const ids=['bBreed','bAge','bFoodQuality','bGrooming','bInsurance','bLifestyle'];if(ids.some(id=>!$(id).value)){$('budgetResult').innerHTML=`<span class="error">${en?'Choose an option in every field.':'Choisis une option dans chaque champ.'}</span>`;return}const factor=breedFactors[$('bBreed').value]||1,food=ranges.food[$('bFoodQuality').value].map(x=>Math.round(x*factor)),vet=ranges.age[$('bAge').value].map(x=>Math.round(x*factor)),groom=ranges.groom[$('bGrooming').value].map(x=>Math.round(x*factor)),insurance=ranges.insurance[$('bInsurance').value],litter=[300,650],gear=[150,350],parasites=$('bLifestyle').value==='secureOutdoor'?[150,350]:[0,80],low=food[0]+vet[0]+groom[0]+insurance[0]+litter[0]+gear[0]+parasites[0],high=food[1]+vet[1]+groom[1]+insurance[1]+litter[1]+gear[1]+parasites[1],fmt=n=>n.toLocaleString(en?'en-CA':'fr-CA');$('budgetResult').innerHTML=`<h3>${$('bBreed').selectedOptions[0].textContent}</h3><div class="budget-total">${fmt(low)}–${fmt(high)} $ / ${en?'year':'an'}</div><div class="budget-lines"><span>${en?'Food':'Alimentation'} : ${fmt(food[0])}–${fmt(food[1])} $</span><span>${en?'Veterinary care':'Soins vétérinaires'} : ${fmt(vet[0])}–${fmt(vet[1])} $</span><span>${en?'Litter':'Litière'} : ${fmt(litter[0])}–${fmt(litter[1])} $</span><span>${en?'Grooming':'Toilettage'} : ${fmt(groom[0])}–${fmt(groom[1])} $</span><span>${en?'Insurance':'Assurance'} : ${fmt(insurance[0])}–${fmt(insurance[1])} $</span><span>${en?'Supplies and prevention':'Matériel et prévention'} : ${fmt(gear[0]+parasites[0])}–${fmt(gear[1]+parasites[1])} $</span></div><p><small>${en?'Indicative Canadian estimate. Emergency care and adoption or purchase costs are not included.':'Estimation canadienne indicative. Les urgences et les frais d’adoption ou d’achat ne sont pas inclus.'}</small></p>`};

const quizFr=[['Pourquoi un chat griffe-t-il?',['Pour marquer et entretenir ses griffes','Uniquement par colère','Pour demander de la nourriture'],0],['Combien de litières conseille-t-on souvent pour deux chats?',['Une','Trois','Aucune'],1],['Un changement soudain de comportement peut indiquer…',['Une douleur','Une nouvelle race','Toujours de la jalousie'],0],['Le jeu de chasse devrait…',['Finir parfois par une récompense','Utiliser les mains','Être forcé'],0],['Un chat qui ne peut pas uriner…',['Peut attendre une semaine','Doit voir rapidement un vétérinaire','A seulement besoin de jouer'],1]],quizEn=[['Why does a cat scratch?',['To mark and maintain its claws','Only because it is angry','To ask for food'],0],['How many litter boxes are often recommended for two cats?',['One','Three','None'],1],['A sudden behaviour change may indicate…',['Pain','A new breed','Always jealousy'],0],['Predatory play should…',['Sometimes end with a reward','Use your hands','Be forced'],0],['A cat that cannot urinate…',['Can wait a week','Needs urgent veterinary care','Only needs to play'],1]];let qi=0,score=0;function showQ(){const qz=en?quizEn:quizFr;if(qi>=qz.length){$('qText').textContent=`${en?'Score':'Résultat'} : ${score}/${qz.length} (${Math.round(score/qz.length*100)} %)`;$('qAnswers').innerHTML='';$('qRestart').hidden=false;return}const q=qz[qi];$('qText').textContent=q[0];$('qAnswers').innerHTML=q[1].map((a,i)=>`<button type="button" data-a="${i}">${a}</button>`).join('');$('qAnswers').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(+b.dataset.a===q[2])score++;$('qFeedback').textContent=+b.dataset.a===q[2]?(en?'Well done!':'Bravo!'):(en?'Not quite.':'Pas tout à fait.');setTimeout(()=>{qi++;$('qFeedback').textContent='';showQ()},900)})}$('qRestart').onclick=()=>{qi=score=0;$('qRestart').hidden=true;showQ()};
const banks={cute:['Mochi','Waffle','Nougat','Poppy','Yuki','Bambi','Cookie','Loulou','Vanille','Flocon'],elegant:['Onyx','Saphir','Rubis','Zéphyr','Cassiopée','Sultan','Topaze','Majesté','Noblesse','Harmonie'],magic:['Luna','Aurore','Stella','Éclipse','Pandora','Céleste','Magic','Galaxie','Mystère','Nova'],fun:['Pixel','Sushi','Taco','Pistache','Moustache','Biscotte','Ninja','Chaussette','Pompom','Mango']};$('makeNames').onclick=()=>{const l=$('nLetter').value.trim().toLowerCase(),names=banks[$('nStyle').value].filter(n=>!l||n.toLowerCase().startsWith(l));$('names').innerHTML=(names.length?names:[en?'No name found':'Aucun nom trouvé']).map(n=>`<span>${n}</span>`).join('')};
function translate(){en=language.value==='en';localStorage.setItem('dicopetsLanguage',en?'en':'fr');document.documentElement.lang=en?'en':'fr';document.querySelectorAll('[data-fr]').forEach(el=>el.textContent=en?el.dataset.en:el.dataset.fr);document.querySelectorAll('select option[value=""]').forEach(o=>o.textContent=en?'Choose…':'Choisir…');fillBreeds();showQ();$('makeNames').click()}
language.value=en?'en':'fr';language.onchange=translate;translate();
})();
