(() => {
  const $=id=>document.getElementById(id);
  const profiles=[
    {name:'Labrador Retriever',size:'large',activity:'high',time:90,experience:'beginner',children:true,groom:'medium',style:'family',homes:['house','land','apartment']},
    {name:'Golden Retriever',size:'large',activity:'high',time:90,experience:'beginner',children:true,groom:'high',style:'family',homes:['house','land']},
    {name:'Caniche standard',size:'large',activity:'high',time:90,experience:'some',children:true,groom:'high',style:'sport',homes:['house','land','apartment']},
    {name:'Cavalier King Charles Spaniel',size:'small',activity:'low',time:45,experience:'beginner',children:true,groom:'medium',style:'family',homes:['apartment','house']},
    {name:'Shih Tzu',size:'small',activity:'low',time:45,experience:'beginner',children:true,groom:'high',style:'family',homes:['apartment','house']},
    {name:'Beagle',size:'medium',activity:'high',time:90,experience:'some',children:true,groom:'low',style:'sport',homes:['house','land']},
    {name:'Border Collie',size:'medium',activity:'high',time:150,experience:'advanced',children:false,groom:'medium',style:'sport',homes:['land']},
    {name:'Berger australien',size:'medium',activity:'high',time:150,experience:'some',children:true,groom:'medium',style:'sport',homes:['house','land']},
    {name:'Eurasier',size:'large',activity:'medium',time:90,experience:'some',children:true,groom:'high',style:'family',homes:['house','land']},
    {name:'Basenji',size:'medium',activity:'high',time:90,experience:'advanced',children:false,groom:'low',style:'independent',homes:['house','apartment']},
    {name:'Chihuahua',size:'small',activity:'low',time:45,experience:'some',children:false,groom:'low',style:'family',homes:['apartment','house']},
    {name:'Chien finnois de Laponie',size:'medium',activity:'high',time:90,experience:'some',children:true,groom:'high',style:'family',homes:['house','land']},
    {name:'Lagotto Romagnolo',size:'medium',activity:'high',time:90,experience:'some',children:true,groom:'high',style:'sport',homes:['house','land']},
    {name:'Terrier tchèque',size:'small',activity:'medium',time:60,experience:'some',children:true,groom:'medium',style:'family',homes:['apartment','house']},
    {name:'Terre-Neuve',size:'large',activity:'medium',time:90,experience:'some',children:true,groom:'high',style:'family',homes:['house','land']}
  ];
  const activityRank={low:1,medium:2,high:3},experienceRank={beginner:1,some:2,advanced:3},groomRank={low:1,medium:2,high:3};
  $('idealSubmit').onclick=()=>{const values={home:$('idealHome').value,activity:$('idealActivity').value,time:Number($('idealTime').value),experience:$('idealExperience').value,children:$('idealChildren').value,size:$('idealSize').value,groom:$('idealGroom').value,style:$('idealStyle').value};if(Object.values(values).some(v=>v===''||v===0)){$('idealResult').className='result open';$('idealResult').textContent='Tu n’as pas rempli toutes les informations.';return}const scored=profiles.map(p=>{let score=0,reasons=[];if(p.homes.includes(values.home)){score+=3;reasons.push('logement compatible')}if(values.size==='any'||p.size===values.size){score+=3;reasons.push('format recherché')}const activityGap=Math.abs(activityRank[p.activity]-activityRank[values.activity]);score+=Math.max(0,3-activityGap*2);if(p.time<=values.time){score+=3;reasons.push('temps quotidien adapté')}if(experienceRank[p.experience]<=experienceRank[values.experience])score+=2;if(values.children==='no'||p.children){score+=2;if(values.children==='yes')reasons.push('profil familial')}if(groomRank[p.groom]<=groomRank[values.groom])score+=2;if(p.style===values.style){score+=3;reasons.push('tempérament recherché')}return {...p,score,reasons}}).sort((a,b)=>b.score-a.score).slice(0,3);$('idealResult').className='result open';$('idealResult').innerHTML='<h3>Les trois profils les plus compatibles</h3><div class="recommendations">'+scored.map((p,i)=>'<article class="recommendation"><small>Compatibilité '+Math.round(p.score/21*100)+' %</small><h3>'+p.name+'</h3><p>'+p.reasons.join(' · ')+'</p><a href="dicochien.html?breed='+encodeURIComponent(p.name)+'">Voir sa fiche →</a></article>').join('')+'</div><p><small>Ce résultat aide à réfléchir, mais chaque chien est un individu. Rencontre-le et discute avec un refuge ou un professionnel avant toute décision.</small></p>'};
  $('budgetSubmit').onclick=()=>{const size=$('budgetSize').value,coat=$('budgetCoat').value,activity=$('budgetActivity').value,breed=$('budgetBreed').value;const breedFactor={standard:1,labrador:1.08,golden:1.12,poodle:1.16,bulldog:1.22,beagle:1,border:1.08,husky:1.12,chihuahua:.9,newfoundland:1.3}[breed];const breedName=$('budgetBreed').selectedOptions[0].textContent;const food=Math.round(({small:650,medium:950,large:1350,giant:1900}[size]+(activity==='high'?180:activity==='very-high'?350:0))*breedFactor),vet=Math.round({small:650,medium:700,large:780,giant:900}[size]*breedFactor),groom=Math.round({easy:180,regular:420,pro:950}[coat]*breedFactor),insurance=Math.round({small:550,medium:680,large:820,giant:1050}[size]*breedFactor),gear={small:320,medium:420,large:520,giant:650}[size],training=350,total=food+vet+groom+insurance+gear+training,low=Math.round(total*.85),high=Math.round(total*1.25);$('budgetResult').className='result open';$('budgetResult').innerHTML='<h3>'+breedName+'</h3><div class="budget-total">'+low.toLocaleString('fr-CA')+' à '+high.toLocaleString('fr-CA')+' $ / an</div><div class="budget-lines"><span>Alimentation : ≈ '+food+' $</span><span>Prévention vétérinaire : ≈ '+vet+' $</span><span>Toilettage : ≈ '+groom+' $</span><span>Assurance : ≈ '+insurance+' $</span><span>Matériel : ≈ '+gear+' $</span><span>Éducation : ≈ '+training+' $</span></div><p><small>La race ajuste l’estimation pour les besoins moyens connus, mais chaque chien est différent. Prévois aussi un fonds d’urgence séparé. Les prix varient selon la région, la santé et les services choisis.</small></p>'};
  const questions=[
    ['Que doit toujours avoir un chien ?',['De l’eau fraîche','Du lait','Du jus'],'De l’eau fraîche'],['Quel professionnel diagnostique une maladie ?',['Le vétérinaire','Le toiletteur','Le promeneur'],'Le vétérinaire'],['Un chien qui se fige peut être…',['Inconfortable','Toujours joyeux','Endormi debout'],'Inconfortable'],['Le rappel se travaille d’abord…',['Dans un lieu calme','Au bord d’une route','Sans récompense'],'Dans un lieu calme'],['Avant de changer de nourriture…',['Faire une transition progressive','Tout changer immédiatement','Faire jeûner trois jours'],'Faire une transition progressive'],['Le chocolat est…',['Toxique pour le chien','Un bon prix','Recommandé après le sport'],'Toxique pour le chien'],['Une laisse détendue se récompense…',['Rapidement','Une semaine plus tard','Jamais'],'Rapidement'],['Les griffes trop longues peuvent…',['Gêner les déplacements','Améliorer la course','Nettoyer les sols'],'Gêner les déplacements'],['Par forte chaleur, il faut…',['Réduire l’effort','Courir à midi','Laisser le chien en voiture'],'Réduire l’effort'],['La socialisation doit être…',['Progressive et positive','Forcée','Punitive'],'Progressive et positive'],['Un changement soudain de comportement mérite…',['Une vérification vétérinaire','D’être ignoré','Une punition'],'Une vérification vétérinaire'],['Le flair est une activité…',['Mentalement stimulante','Inutile','Réservée aux chiots'],'Mentalement stimulante'],['Le poids idéal se surveille avec…',['La silhouette et le vétérinaire','La couleur du collier','La longueur de la queue'],'La silhouette et le vétérinaire'],['Un chien qui revient au rappel doit être…',['Récompensé','Puni pour le délai','Ignoré'],'Récompensé'],['Avant une adoption, il faut considérer…',['Temps, budget et besoins','Seulement la couleur','Seulement le nom'],'Temps, budget et besoins']
  ];let qi=0,score=0,locked=false;
  function drawQuiz(){if(qi>=questions.length){finishQuiz();return}locked=false;const q=questions[qi];$('quizProgress').textContent='Question '+(qi+1)+' / '+questions.length;$('quizQuestion').textContent=q[0];$('quizAnswers').innerHTML=q[1].map(a=>'<button>'+a+'</button>').join('');$('quizFeedback').textContent='';$('quizAnswers').querySelectorAll('button').forEach(b=>b.onclick=()=>answerQuiz(b.textContent));}
  function answerQuiz(answer){if(locked)return;locked=true;const good=answer===questions[qi][2];if(good)score++;$('quizFeedback').textContent=good?'Bravo, bonne réponse !':'Bonne réponse : '+questions[qi][2];setTimeout(()=>{qi++;drawQuiz()},1100)}
  async function finishQuiz(){const percent=Math.round(score/questions.length*100);$('quizProgress').textContent='Quiz terminé';$('quizQuestion').textContent=score+' / '+questions.length+' — '+percent+' %';$('quizAnswers').innerHTML='';$('quizFeedback').textContent=percent>=80?'Badge « Expert canin » débloqué !':'Recommence pour atteindre 80 % et débloquer le badge.';$('quizRestart').hidden=false;if(percent>=80){const badges=JSON.parse(localStorage.getItem('dcBadges')||'[]');if(!badges.includes('Expert canin')){badges.push('Expert canin');localStorage.setItem('dcBadges',JSON.stringify(badges));window.dispatchEvent(new Event('dc-badges-changed'))}try{const db=window.supabase.createClient('https://mmxdlnfntpufwwkdvgzc.supabase.co','sb_publishable_Pa-DX3nwNTZktbWK46KDQg_IuIy8TZP'),{data}=await db.auth.getUser();if(data.user){const list=Array.isArray(data.user.user_metadata?.dog_badges)?data.user.user_metadata.dog_badges:[];if(!list.includes('Expert canin'))await db.auth.updateUser({data:{dog_badges:[...list,'Expert canin'],dog_quiz_best:Math.max(percent,Number(data.user.user_metadata?.dog_quiz_best||0))}})}}catch(_){}}}
  $('quizRestart').onclick=()=>{qi=0;score=0;$('quizRestart').hidden=true;drawQuiz()};drawQuiz();
  const names={cute:'Mochi,Nougat,Waffle,Loulou,Poppy,Bambi,Cookie,Yuki,Vanille,Mocha,Flocon,Doudou,Kiwi,Tempo,Diabolo,Perle',elegant:'Cassiopée,Rubis,Saphir,Émeraude,Zéphir,Majesté,Sultan,Onyx,Topaze,Harmonie,Noblesse,Velours,Opale',sport:'Tonnerre,Legend,Champion,Éclair,Hurricane,Jazz,Lucky,Aventure,Légende,Dash,Flash,Rocket,Storm,Volt',nature:'Willow,Maple,Cèdre,Forêt,Océan,Neige,Brume,Soleil,Lune,Rivage,Orage,Meadow,Flora',magic:'Aurore,Céleste,Galaxie,Luna,Eclipse,Magic,Mystère,Pandora,Stella,Belle,Étoile,Mélodie,Comète',food:'Muffin,Biscuit,Caramel,Cannelle,Praline,Pistache,Churro,Peanut,Taco,Brownie,Toffee,Olive,Truffe'};
  'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('').forEach(l=>$('nameLetter').insertAdjacentHTML('beforeend','<option>'+l+'</option>'));
  function makeNames(){const letter=$('nameLetter').value;let pool=names[$('nameTheme').value].split(',');if(letter)pool=pool.filter(n=>n.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().startsWith(letter));$('nameResults').innerHTML=(pool.length?pool:['Aucun nom pour cette lettre']).map(n=>'<span>'+n+'</span>').join('')}$('nameGenerate').onclick=makeNames;makeNames();
})();

(() => {
  const $=id=>document.getElementById(id);
  const dogs=[
    ['Welsh Corgi Pembroke','small','high',75,'some',true,'medium','family',['apartment','house','land']],
    ['Labrador Retriever','large','high',100,'beginner',true,'medium','family',['house','land']],
    ['Golden Retriever','large','high',105,'beginner',true,'high','family',['house','land']],
    ['Caniche standard','large','high',90,'some',true,'high','sport',['apartment','house','land']],
    ['Cavalier King Charles Spaniel','small','low',45,'beginner',true,'medium','family',['apartment','house']],
    ['Shih Tzu','small','low',40,'beginner',true,'high','family',['apartment','house']],
    ['Bouledogue français','small','low',40,'beginner',true,'low','family',['apartment','house']],
    ['Chihuahua','small','low',35,'some',false,'low','independent',['apartment','house']],
    ['Terrier tchèque','small','medium',60,'some',true,'medium','family',['apartment','house']],
    ['Jack Russell Terrier','small','high',90,'advanced',false,'low','sport',['house','land']],
    ['Beagle','medium','high',90,'some',true,'low','independent',['house','land']],
    ['Border Collie','medium','high',150,'advanced',false,'medium','sport',['land']],
    ['Berger australien','medium','high',130,'some',true,'medium','sport',['house','land']],
    ['Chien finnois de Laponie','medium','medium',90,'some',true,'high','family',['house','land']],
    ['Lagotto Romagnolo','medium','high',100,'some',true,'high','sport',['house','land']],
    ['Basenji','medium','high',90,'advanced',false,'low','independent',['apartment','house']],
    ['Eurasier','large','medium',75,'some',true,'high','family',['house','land']],
    ['Boxer','large','high',90,'some',true,'low','sport',['house','land']],
    ['Husky sibérien','large','high',140,'advanced',false,'high','independent',['land']],
    ['Terre-Neuve','large','medium',75,'some',true,'high','family',['house','land']]
  ].map(([name,size,activity,time,experience,children,groom,style,homes])=>({name,size,activity,time,experience,children,groom,style,homes}));
  dogs.push(
    {name:'Welsh Corgi Cardigan',size:'small',activity:'high',time:80,experience:'some',children:true,groom:'medium',style:'family',homes:['apartment','house','land']},
    {name:'Cavapoo',size:'small',activity:'medium',time:60,experience:'beginner',children:true,groom:'high',style:'family',homes:['apartment','house']},
    {name:'Cockapoo',size:'medium',activity:'high',time:80,experience:'some',children:true,groom:'high',style:'family',homes:['apartment','house','land']},
    {name:'Bichon maltais',size:'small',activity:'low',time:45,experience:'beginner',children:true,groom:'high',style:'family',homes:['apartment','house']},
    {name:'Basset Hound',size:'medium',activity:'medium',time:60,experience:'some',children:true,groom:'low',style:'independent',homes:['apartment','house']},
    {name:'Bichon frisé',size:'small',activity:'medium',time:55,experience:'beginner',children:true,groom:'high',style:'family',homes:['apartment','house']},
    {name:'Samoyède',size:'large',activity:'high',time:110,experience:'some',children:true,groom:'high',style:'family',homes:['house','land']},
    {name:'Schnauzer nain',size:'small',activity:'high',time:75,experience:'some',children:true,groom:'high',style:'sport',homes:['apartment','house']},
    {name:'Shiba Inu',size:'medium',activity:'high',time:80,experience:'advanced',children:false,groom:'medium',style:'independent',homes:['apartment','house']},
    {name:'Whippet',size:'medium',activity:'medium',time:65,experience:'beginner',children:true,groom:'low',style:'family',homes:['apartment','house']}
  );
  const appearance={
    'Welsh Corgi Pembroke':['cute','short'],'Labrador Retriever':['athletic','short'],'Golden Retriever':['elegant','long'],'Caniche standard':['elegant','curly'],'Cavalier King Charles Spaniel':['cute','long'],'Shih Tzu':['cute','long'],'Bouledogue français':['massive','short'],'Chihuahua':['cute','short'],'Terrier tchèque':['athletic','long'],'Jack Russell Terrier':['athletic','short'],'Beagle':['cute','short'],'Border Collie':['athletic','long'],'Berger australien':['athletic','long'],'Chien finnois de Laponie':['cute','long'],'Lagotto Romagnolo':['cute','curly'],'Basenji':['elegant','short'],'Eurasier':['massive','long'],'Boxer':['massive','short'],'Husky sibérien':['athletic','long'],'Terre-Neuve':['massive','long'],'Welsh Corgi Cardigan':['cute','short'],'Cavapoo':['cute','curly'],'Cockapoo':['cute','curly'],'Bichon maltais':['elegant','long'],'Basset Hound':['massive','short'],'Bichon frisé':['cute','curly'],'Samoyède':['massive','long'],'Schnauzer nain':['athletic','short'],'Shiba Inu':['elegant','short'],'Whippet':['elegant','short']
  };dogs.forEach(d=>{[d.look,d.coat]=appearance[d.name]||['athletic','short']});
  const idealGrid=$('idealSubmit').previousElementSibling;idealGrid.insertAdjacentHTML('beforeend','<label>Apparence recherchée<select id="idealLook"><option value="">Choisir…</option><option value="cute">Mignon</option><option value="elegant">Élégant</option><option value="athletic">Athlétique</option><option value="massive">Grand et massif</option></select></label><label>Type de poil souhaité<select id="idealCoat"><option value="">Choisir…</option><option value="short">Court</option><option value="long">Long</option><option value="curly">Frisé ou bouclé</option></select></label>');
  const rank={low:1,medium:2,high:3,beginner:1,some:2,advanced:3};
  const ids=['idealHome','idealActivity','idealTime','idealExperience','idealChildren','idealSize','idealGroom','idealStyle','idealLook','idealCoat'];
  const complete=()=>ids.every(id=>$(id)?.value);
  function recommend(){
    if(!complete()){$('idealResult').className='result open';$('idealResult').textContent='Tu n’as pas rempli toutes les informations.';return;}
    const v={home:$('idealHome').value,activity:$('idealActivity').value,time:+$('idealTime').value,experience:$('idealExperience').value,children:$('idealChildren').value,size:$('idealSize').value,groom:$('idealGroom').value,style:$('idealStyle').value,look:$('idealLook').value,coat:$('idealCoat').value};
    const results=dogs.map(d=>{let score=0,reasons=[],warnings=[];
      if(d.homes.includes(v.home)){score+=14;reasons.push('logement adapté')}else{score-=22;warnings.push('logement moins adapté')}
      const ag=Math.abs(rank[d.activity]-rank[v.activity]);if(!ag){score+=22;reasons.push('niveau d’activité très proche')}else if(ag===1){score+=3;warnings.push('énergie à ajuster')}else{score-=24;warnings.push('niveau d’activité très différent')}
      const timeGap=v.time-d.time;if(timeGap>=0){score+=20;reasons.push('temps quotidien suffisant')}else if(timeGap>=-30){score-=7;warnings.push('temps quotidien un peu court')}else{score-=32;warnings.push('temps quotidien insuffisant')}
      if(rank[v.experience]>=rank[d.experience]){score+=14;reasons.push('expérience compatible')}else{score-=28;warnings.push('race plus exigeante que ton expérience')}
      if(v.children==='yes'&&!d.children){score-=40;warnings.push('profil moins indiqué avec des enfants')}else{score+=12;if(v.children==='yes')reasons.push('profil familial')}
      if(v.size==='any'){score+=4}else if(v.size===d.size){score+=20;reasons.push('taille recherchée')}else{score-=18;warnings.push('taille différente')}
      if(rank[v.groom]>=rank[d.groom]){score+=12;reasons.push('entretien accepté')}else{score-=18;warnings.push('toilettage plus exigeant')}
      if(v.style===d.style){score+=18;reasons.push('tempérament recherché')}else{score-=8;warnings.push('style de relation différent')}
      if(v.look===d.look){score+=18;reasons.push('apparence recherchée')}else{score-=10;warnings.push('silhouette différente')}
      if(v.coat===d.coat){score+=18;reasons.push('type de poil recherché')}else{score-=14;warnings.push('pelage différent')}
      return {...d,score,reasons,warnings,percent:Math.max(5,Math.min(98,Math.round((score+70)/2.4)))};
    }).sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name,'fr')).slice(0,3);
    $('idealResult').className='result open';$('idealResult').innerHTML='<h3>Les profils les plus compatibles avec tes réponses actuelles</h3><div class="recommendations">'+results.map(d=>'<article class="recommendation"><small>Compatibilité estimée '+d.percent+' %</small><h3>'+d.name+'</h3><p><strong>Points forts :</strong> '+d.reasons.slice(0,4).join(' · ')+'</p><p><strong>À vérifier :</strong> '+(d.warnings.slice(0,2).join(' · ')||'aucun écart important')+'</p><a href="dicochien.html?section=races&breed='+encodeURIComponent(d.name)+'">Voir sa fiche →</a></article>').join('')+'</div><p><small>Le classement est recalculé avec chaque réponse. Il reste indicatif : le caractère individuel, la santé et l’histoire du chien comptent aussi.</small></p>';
  }
  $('idealSubmit').onclick=recommend;ids.forEach(id=>$(id)?.addEventListener('change',()=>{if(complete())recommend()}));

  const breedSelect=$('budgetBreed');if(breedSelect&&!breedSelect.querySelector('[value="corgi"]'))breedSelect.insertAdjacentHTML('afterbegin','<option value="corgi">Welsh Corgi Pembroke</option>');
  const presets={corgi:['small','regular','high',1.05],labrador:['large','easy','high',1.08],golden:['large','regular','high',1.12],poodle:['large','pro','high',1.16],bulldog:['small','easy','moderate',1.22],beagle:['medium','easy','high',1],border:['medium','regular','very-high',1.08],husky:['medium','regular','very-high',1.12],chihuahua:['small','easy','moderate',.9],newfoundland:['giant','regular','moderate',1.3],standard:[null,null,null,1]};
  function calculate(){const breed=breedSelect.value,size=$('budgetSize').value,coat=$('budgetCoat').value,activity=$('budgetActivity').value,factor=presets[breed]?.[3]||1,name=breedSelect.selectedOptions[0].textContent;const food=Math.round(({small:650,medium:950,large:1350,giant:1900}[size]+({moderate:0,high:180,'very-high':350}[activity]))*factor),vet=Math.round({small:650,medium:700,large:780,giant:900}[size]*factor),groom=Math.round({easy:180,regular:420,pro:950}[coat]*factor),insurance=Math.round({small:550,medium:680,large:820,giant:1050}[size]*factor),gear={small:320,medium:420,large:520,giant:650}[size],training=350,total=food+vet+groom+insurance+gear+training,low=Math.round(total*.85),high=Math.round(total*1.25);$('budgetResult').className='result open';$('budgetResult').innerHTML='<h3>'+name+'</h3><div class="budget-total">'+low.toLocaleString('fr-CA')+' à '+high.toLocaleString('fr-CA')+' $ / an</div><div class="budget-lines"><span>Alimentation : ≈ '+food+' $</span><span>Prévention vétérinaire : ≈ '+vet+' $</span><span>Toilettage : ≈ '+groom+' $</span><span>Assurance : ≈ '+insurance+' $</span><span>Matériel : ≈ '+gear+' $</span><span>Éducation : ≈ '+training+' $</span></div><p><small>Le résultat se met à jour dès qu’un choix change. Il s’agit d’une estimation canadienne; garde un fonds d’urgence séparé.</small></p>';}
  breedSelect.onchange=()=>{const p=presets[breedSelect.value];if(p?.[0]){$('budgetSize').value=p[0];$('budgetCoat').value=p[1];$('budgetActivity').value=p[2]}calculate()};$('budgetSubmit').onclick=calculate;['budgetSize','budgetCoat','budgetActivity'].forEach(id=>$(id).addEventListener('change',calculate));
})();

(() => {
  const $=id=>document.getElementById(id),select=$('budgetBreed');
  const catalog=[
    ['Akita','large','regular','high',1.16],['Azawakh','large','easy','high',1.05],['Basenji','medium','easy','high',1],['Basset Hound','medium','easy','moderate',1.08],['Beagle','medium','easy','high',1],['Berger allemand','large','regular','very-high',1.13],['Berger australien','medium','regular','very-high',1.1],['Berger belge malinois','large','easy','very-high',1.12],['Berger de Bohême','medium','regular','high',1.06],['Bichon frisé','small','pro','moderate',1.08],['Bichon maltais','small','pro','moderate',1.08],['Border Collie','medium','regular','very-high',1.08],['Bouledogue français','small','easy','moderate',1.22],['Bouvier bernois','giant','regular','moderate',1.25],['Boxer','large','easy','high',1.14],['Caniche standard','large','pro','high',1.16],['Carlin','small','easy','moderate',1.18],['Cavalier King Charles Spaniel','small','regular','moderate',1.14],['Cavapoo','small','pro','moderate',1.12],['Chien d’eau portugais','large','pro','high',1.13],['Chien finnois de Laponie','medium','regular','high',1.08],['Chihuahua','small','easy','moderate',.9],['Chinook','large','regular','high',1.08],['Cocker anglais','medium','pro','high',1.1],['Cockapoo','medium','pro','high',1.13],['Dalmatien','large','easy','very-high',1.1],['Dobermann','large','easy','very-high',1.14],['Épagneul nain continental Papillon','small','regular','high',.98],['Eurasier','large','regular','moderate',1.12],['Golden Retriever','large','regular','high',1.12],['Husky sibérien','medium','regular','very-high',1.12],['Jack Russell Terrier','small','easy','very-high',.98],['Kai Ken','medium','regular','high',1.04],['Kooikerhondje','medium','regular','high',1.04],['Labrador Retriever','large','easy','high',1.08],['Lagotto Romagnolo','medium','pro','high',1.1],['Lévrier afghan','large','pro','high',1.18],['Mudi','medium','regular','very-high',1.04],['Otterhound','giant','pro','high',1.24],['Pumi','medium','pro','very-high',1.06],['Rottweiler','large','easy','high',1.18],['Samoyède','large','pro','high',1.18],['Schipperke','small','regular','high',.98],['Schnauzer nain','small','pro','high',1.05],['Shiba Inu','medium','regular','high',1.08],['Shih Tzu','small','pro','moderate',1.1],['Teckel standard','small','easy','moderate',1.05],['Terre-Neuve','giant','regular','moderate',1.3],['Terrier tchèque','small','pro','moderate',1.02],['Thai Ridgeback','large','easy','high',1.08],['Welsh Corgi Cardigan','small','regular','high',1.06],['Welsh Corgi Pembroke','small','regular','high',1.05],['Whippet','medium','easy','high',1],['Xoloitzcuintle moyen','medium','easy','high',1.02],['Yorkshire Terrier','small','pro','moderate',1.05]
  ].sort((a,b)=>a[0].localeCompare(b[0],'fr'));
  select.innerHTML=catalog.map((d,i)=>`<option value="dog-${i}">${d[0]}</option>`).join('');
  function budget(){const dog=catalog[+select.value.replace('dog-','')],size=$('budgetSize').value,coat=$('budgetCoat').value,activity=$('budgetActivity').value,factor=dog[4];const food=Math.round(({small:650,medium:950,large:1350,giant:1900}[size]+({moderate:0,high:180,'very-high':350}[activity]))*factor),vet=Math.round({small:650,medium:700,large:780,giant:900}[size]*factor),groom=Math.round({easy:180,regular:420,pro:950}[coat]*factor),insurance=Math.round({small:550,medium:680,large:820,giant:1050}[size]*factor),gear={small:320,medium:420,large:520,giant:650}[size],training=350,total=food+vet+groom+insurance+gear+training,low=Math.round(total*.85),high=Math.round(total*1.25);$('budgetResult').className='result open';$('budgetResult').innerHTML='<h3>'+dog[0]+'</h3><div class="budget-total">'+low.toLocaleString('fr-CA')+' à '+high.toLocaleString('fr-CA')+' $ / an</div><div class="budget-lines"><span>Alimentation : ≈ '+food+' $</span><span>Prévention vétérinaire : ≈ '+vet+' $</span><span>Toilettage : ≈ '+groom+' $</span><span>Assurance : ≈ '+insurance+' $</span><span>Matériel : ≈ '+gear+' $</span><span>Éducation : ≈ '+training+' $</span></div><p><small>Estimation canadienne indicative selon la race et les choix affichés. Prévois aussi un fonds d’urgence séparé.</small></p>';}
  select.onchange=()=>{const d=catalog[+select.value.replace('dog-','')];$('budgetSize').value=d[1];$('budgetCoat').value=d[2];$('budgetActivity').value=d[3];budget()};$('budgetSubmit').onclick=budget;['budgetSize','budgetCoat','budgetActivity'].forEach(id=>$(id).addEventListener('change',budget));select.value='dog-0';select.onchange();

  const routeLinks={ideal:'Mon chien idéal',education:'Éducation',budget:'Budget',quiz:'Quiz',noms:'Noms'};document.querySelectorAll('.top a[href^="#"]').forEach(link=>{const key=link.getAttribute('href').slice(1);if(key==='soins')link.href='soins-chien.html';else if(routeLinks[key])link.href='outils-chien.html?outil='+key});
  let route=new URLSearchParams(location.search).get('outil')||location.hash.slice(1)||'ideal';if(route==='soins'){location.replace('soins-chien.html');return}if(!routeLinks[route])route='ideal';
  document.querySelector('.hero').style.display='none';document.querySelectorAll('main > section').forEach(section=>section.style.display=section.id===route?'block':'none');document.title=routeLinks[route]+' · DicoChien';window.scrollTo(0,0);
})();
