const css=`
body{font-family:Inter,Arial,sans-serif!important;background:#f7faff!important}.nav{box-shadow:0 3px 14px #214a9a18}.nav a{font-size:13px!important}.section{padding:76px 0!important}.photo-panel{position:relative;overflow:hidden;border-radius:18px;min-height:440px;background:#123;color:white;box-shadow:0 14px 34px #214a9a22}.photo-panel img{width:100%;height:440px;object-fit:cover;display:block;filter:brightness(.75)}.photo-panel .labels{position:absolute;inset:0}.label{position:absolute;background:#fff;color:#214a9a;padding:8px 11px;border-radius:99px;font-size:12px;font-weight:800;box-shadow:0 4px 14px #0016}.label:after{content:'';position:absolute;width:45px;height:2px;background:#e85091;top:50%;left:100%}.subnav{display:flex;gap:10px;flex-wrap:wrap;margin:20px 0}.subnav button{background:#fff;color:#214a9a;border:1px solid #bdd0ed;border-radius:99px}.subnav button.active{background:#214a9a;color:#fff}.discipline-panel{display:none;grid-template-columns:repeat(3,1fr);gap:16px}.discipline-panel.active{display:grid}.discipline-panel article{background:#fff;padding:26px;border-radius:14px;border:1px solid #dce6f5}.discipline-panel h3{margin:0;color:#214a9a}.gloss-promo{background:linear-gradient(110deg,#214a9a,#5b94df);padding:38px;border-radius:18px;color:white;display:flex;justify-content:space-between;gap:30px;align-items:center}.gloss-promo h3{font-size:34px;margin:0}.robe-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.robe{background:#fff;padding:18px;border-radius:12px;border:1px solid #d7e2f2}.swatches{display:flex;gap:6px;margin-bottom:13px}.swatch{width:32px;height:32px;border-radius:50%;border:2px solid #fff;box-shadow:0 0 0 1px #cbd8eb}.robe h3{font-size:22px;margin:4px 0}.robe small{color:#637694}@media(max-width:720px){.discipline-panel.active,.robe-grid{grid-template-columns:1fr 1fr}.gloss-promo{display:block}.gloss-promo a{margin-top:18px}.photo-panel,.photo-panel img{min-height:330px;height:330px}}`;
document.head.insertAdjacentHTML('beforeend','<style>'+css+'</style>');
document.querySelector('.nav .wrap').innerHTML='<a href="#accueil">Accueil</a><a href="#races">Races</a><a href="#disciplines">Disciplines</a><a href="#soins">Soins</a><a href="#eq-cheval">Ã‰quipement du cheval</a><a href="#eq-cavalier">Ã‰quipement du cavalier</a><a href="#anatomie">Anatomie</a><a href="#robes">Robes</a><a href="glossaire.html">Glossaire</a><a href="#metiers">MÃ©tiers</a><a href="#quiz">Quiz</a>';
document.querySelector('#disciplines .wrap').innerHTML=`<div class="head"><h2>Disciplines</h2><p>Choisissez un univers pour voir uniquement ses disciplines.</p></div><div class="subnav"><button class="active" data-d="classique">Ã‰quitation classique</button><button data-d="western2">Ã‰quitation western</button></div><div id="classique" class="discipline-panel active"><article><h3>Dressage</h3><p>PrÃ©cision, souplesse et connexion avec le cheval.</p></article><article><h3>Saut dâ€™obstacles</h3><p>Franchir un parcours avec rythme et confiance.</p></article><article><h3>Concours complet</h3><p>Dressage, cross et saut dans une mÃªme discipline.</p></article><article><h3>Endurance</h3><p>Longues distances avec une gestion attentive du cheval.</p></article><article><h3>Voltige</h3><p>Gymnastique et expression artistique Ã  cheval.</p></article><article><h3>Attelage</h3><p>Conduire une voiture tirÃ©e par un ou plusieurs chevaux.</p></article></div><div id="western2" class="discipline-panel"><article><h3>Reining</h3><p>Figures prÃ©cises inspirÃ©es du travail de ranch.</p></article><article><h3>Barrel racing</h3><p>Parcours rapide autour de trois tonneaux.</p></article><article><h3>Trail</h3><p>Obstacles inspirÃ©s des sorties en extÃ©rieur.</p></article><article><h3>Cutting</h3><p>Isoler une vache du troupeau avec son cheval.</p></article><article><h3>Western pleasure</h3><p>PrÃ©sentation harmonieuse et dÃ©tendue.</p></article><article><h3>Ranch riding</h3><p>Cheval polyvalent dans un travail de ranch.</p></article></div>`;
document.querySelectorAll('.subnav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.subnav button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.discipline-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.d).classList.add('active')});
function photo(id,title,text,url,labels){document.querySelector(id+' .wrap').innerHTML=`<div class="head"><h2>${title}</h2><p>${text}</p></div><div class="photo-panel"><img src="${url}" alt="${title}"><div class="labels">${labels}</div></div>`}
photo('#eq-cheval','Ã‰quipement du cheval','Les piÃ¨ces principales sur un cheval prÃ©parÃ© pour monter.','https://images.pexels.com/photos/1996333/pexels-photo-1996333.jpeg?auto=compress&cs=tinysrgb&w=1400','<span class="label" style="top:22%;left:61%">Bride</span><span class="label" style="top:36%;left:43%">Selle</span><span class="label" style="top:51%;left:37%">Tapis</span><span class="label" style="top:67%;left:52%">Sangle</span><span class="label" style="top:73%;left:21%">GuÃªtres</span>');
photo('#eq-cavalier','Ã‰quipement du cavalier','Casque, bottes et tenue adaptÃ©e : des indispensables pour la sÃ©curitÃ©.','https://images.pexels.com/photos/1996332/pexels-photo-1996332.jpeg?auto=compress&cs=tinysrgb&w=1400','<span class="label" style="top:12%;left:58%">Casque</span><span class="label" style="top:43%;left:55%">Gilet</span><span class="label" style="top:67%;left:52%">Pantalon</span><span class="label" style="top:81%;left:56%">Bottes</span>');
photo('#anatomie','Anatomie du cheval','Les principales zones Ã  repÃ©rer sur le corps du cheval.','https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?auto=format&fit=crop&w=1400&q=90','<span class="label" style="top:21%;left:61%">TÃªte</span><span class="label" style="top:33%;left:51%">Encolure</span><span class="label" style="top:45%;left:35%">Dos</span><span class="label" style="top:66%;left:27%">Membre</span><span class="label" style="top:51%;left:67%">Croupe</span>');
document.querySelector('#glossaire .wrap').innerHTML='<div class="gloss-promo"><div><h3>Glossaire Ã©questre</h3><p>Plus de 100 mots, dÃ©finitions et termes Ã  connaÃ®tre. Ouvrez le glossaire pour chercher facilement le mot qui vous manque.</p></div><a class="btn" href="glossaire.html">Ouvrir le glossaire â†’</a></div>';
const robes=[['Noir','#24252b','#17181c','Corps noir, crins noirs'],['Bai','#743e24','#24201c','Corps brun, crins noirs'],['Alezan','#b65024','#b65024','Corps et crins fauves'],['Gris','#bfc2c8','#c3c5c8','Poils blancs ou gris'],['Isabelle','#d9b273','#25201a','Corps dorÃ©, crins noirs'],['Palomino','#e4c36f','#f7e6bc','Corps dorÃ©, crins trÃ¨s clairs'],['CafÃ© au lait','#c69a75','#c69a75','Corps et crins beige brun'],['Rouan','#88635d','#313037','MÃ©lange de poils blancs'],['Pie noir','#f7f7f7','#202128','Grandes taches blanches et noires'],['Pie bai','#f7f7f7','#743e24','Grandes taches blanches et baies'],['Appaloosa','#f4eee4','#6d412b','Taches contrastÃ©es'],['Louvet','#b79a65','#302a22','Corps fauve, crins foncÃ©s']];
const robeSec=document.createElement('section');robeSec.id='robes';robeSec.className='section tint';robeSec.innerHTML='<div class="wrap"><div class="head"><h2>Robes des chevaux</h2><p>La robe dÃ©crit la couleur du corps et des crins. Voici les grands types Ã  reconnaÃ®tre.</p></div><div class="robe-grid">'+robes.map(r=>`<article class="robe"><div class="swatches"><i class="swatch" style="background:${r[1]}"></i><i class="swatch" style="background:${r[2]}"></i></div><h3>${r[0]}</h3><small>${r[3]}</small></article>`).join('')+'</div></div>';document.getElementById('metiers').before(robeSec);

const link=document.createElement('link');link.rel='stylesheet';link.href='https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&family=Playfair+Display:wght@600;700&display=swap';document.head.appendChild(link);
document.head.insertAdjacentHTML('beforeend',`<style>:root{--blue:#1f4737!important;--pink:#b98742!important;--sky:#e4eee7!important;--rose:#f3ead9!important;--ink:#213329!important}body{font-family:Manrope,Arial,sans-serif!important;background:#fafaf6!important}.brand,h1,h2,h3{font-family:'Playfair Display',Georgia,serif!important}.brand{color:#1f4737!important}.brand b{color:#b98742!important}.top,.footer{background:#173526!important}.search{background:#e4eee7!important}.nav{background:#fffdf8!important}.nav a{font-family:Manrope,Arial,sans-serif!important;font-weight:800!important;letter-spacing:.01em}.btn,button{background:#b98742!important}.nav a:hover{color:#b98742!important}.label{color:#1f4737!important}.label:after{background:#b98742!important}.photo-panel{background:#173526!important}.discipline-panel h3,.term b{color:#1f4737!important}.subnav button.active{background:#1f4737!important}.robe{border-color:#dce5d8!important}.modal article{font-family:Manrope,Arial,sans-serif}.modal h2{font-family:'Playfair Display',Georgia,serif!important}</style>`);
function newPhoto(id,title,text,url,labels){document.querySelector(id+' .wrap').innerHTML=`<div class="head"><h2>${title}</h2><p>${text}</p></div><div class="photo-panel"><img src="${url}" alt="${title}"><div class="labels">${labels}</div></div>`}
newPhoto('#eq-cheval','Ã‰quipement du cheval','Un cheval montÃ© et Ã©quipÃ© : les Ã©tiquettes indiquent oÃ¹ se trouvent les principales piÃ¨ces.','https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=1600&q=90','<span class="label" style="top:22%;left:60%">Bride</span><span class="label" style="top:39%;left:43%">Selle</span><span class="label" style="top:54%;left:36%">Tapis</span><span class="label" style="top:65%;left:51%">Sangle</span><span class="label" style="top:75%;left:23%">GuÃªtres</span>');
newPhoto('#eq-cavalier','Ã‰quipement du cavalier','Une cavaliÃ¨re Ã©quipÃ©e : casque, gilet, pantalon et bottes sont repÃ©rÃ©s directement sur la photo.','https://images.unsplash.com/photo-1544717684-6a7c6f6d87d2?auto=format&fit=crop&w=1600&q=90','<span class="label" style="top:14%;left:62%">Casque</span><span class="label" style="top:42%;left:58%">Gilet</span><span class="label" style="top:66%;left:58%">Pantalon</span><span class="label" style="top:82%;left:56%">Bottes</span>');
newPhoto('#anatomie','Anatomie du cheval','Les zones sont placÃ©es selon leur position rÃ©elle sur le corps du cheval.','https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?auto=format&fit=crop&w=1600&q=90','<span class="label" style="top:20%;left:65%">TÃªte</span><span class="label" style="top:32%;left:55%">Encolure</span><span class="label" style="top:42%;left:43%">Dos</span><span class="label" style="top:48%;left:27%">Croupe</span><span class="label" style="top:75%;left:35%">Membre</span>');

const theme=`<style>:root{--blue:#234238!important;--pink:#b58a4b!important;--sky:#edf2ea!important;--rose:#f5f0e6!important;--ink:#24362e!important}.top,.footer{background:#1b352d!important}.hero{background:linear-gradient(120deg,#1b352d,#426756,#b58a4b)!important}.search,.tint{background:#edf2ea!important}.rose{background:#f5f0e6!important}.nav{background:#fffdf8!important}.nav a{font-family:Manrope,Arial,sans-serif!important;font-weight:800!important;letter-spacing:.01em}.btn,button{background:#b58a4b!important}.nav a:hover{color:#b58a4b!important}.brand{color:#234238!important}.brand span,.brand b{color:#b58a4b!important}.equip-grid{display:grid;grid-template-columns:1fr 1fr;gap:22px}.equip-card{background:#fff;border-radius:16px;overflow:hidden;border:1px solid #d7e0d5}.equip-card img{display:block;width:100%;height:340px;object-fit:cover}.equip-card.portrait img{height:520px;object-fit:cover}.equip-card div{padding:18px}.equip-card h3{margin:0 0 7px;color:#234238}.anatomy-figure{position:relative;background:#fff;border-radius:16px;overflow:hidden;border:1px solid #d7e0d5}.anatomy-figure img{display:block;width:100%}.anatomy-figure svg{position:absolute;inset:0;width:100%;height:100%}.anatomy-figure line{stroke:#b58a4b;stroke-width:3}.anatomy-figure rect{fill:#fffdf8;stroke:#b58a4b;stroke-width:2}.anatomy-figure text{fill:#234238;font:700 21px Manrope,Arial}.anatomy-note{padding:16px 20px;margin:0;background:#fffdf8;color:#53695e}.subtle{color:#63756a}@media(max-width:720px){.equip-grid{grid-template-columns:1fr}.equip-card img{height:280px}.equip-card.portrait img{height:460px}.anatomy-figure text{font-size:16px}}</style>`;document.head.insertAdjacentHTML('beforeend',theme);document.title='Dicocheval â€” Le guide Ã©questre';const brand=document.querySelector('.brand');if(brand)brand.innerHTML='Dico<span>cheval</span>';
document.querySelector('#eq-cheval .wrap').innerHTML=`<div class="head"><h2>Ã‰quipement du cheval</h2><p>Deux univers bien sÃ©parÃ©s : classique et western.</p></div><div class="equip-grid"><article class="equip-card"><img src="assets/equip-cheval-classique.webp" alt="Cheval Ã©quipÃ© en Ã©quitation classique"><div><h3>Ã‰quitation classique</h3><p>On distingue la bride, le bonnet, la selle, le tapis de selle, la sangle et les guÃªtres.</p></div></article><article class="equip-card"><img src="assets/equip-cheval-western.webp" alt="Cheval Ã©quipÃ© en Ã©quitation western"><div><h3>Ã‰quitation western</h3><p>La selle western, le filet, les rÃªnes et les Ã©triers sont adaptÃ©s au travail et au confort en extÃ©rieur.</p></div></article></div>`;
document.querySelector('#eq-cavalier .wrap').innerHTML=`<div class="head"><h2>Ã‰quipement de la cavaliÃ¨re</h2><p>Deux tenues prÃ©sentÃ©es en format portrait.</p></div><div class="equip-grid"><article class="equip-card portrait"><img src="assets/equip-cavaliere-classique.webp" alt="CavaliÃ¨re en tenue classique"><div><h3>Tenue classique</h3><p>Casque, polo, pantalon dâ€™Ã©quitation et bottes hautes forment une tenue adaptÃ©e Ã  la pratique classique.</p></div></article><article class="equip-card portrait"><img src="assets/equip-cavaliere-western.webp" alt="CavaliÃ¨re en tenue western"><div><h3>Tenue western</h3><p>Chapeau, chemise, jean, boots et selle western sont typiques de cet univers.</p></div></article></div>`;
document.querySelector('#anatomie .wrap').innerHTML=`<div class="head"><h2>Anatomie du cheval</h2><p>RepÃ¨res replacÃ©s sur la vraie silhouette de la photo.</p></div><figure class="anatomy-figure"><img src="assets/anatomie-cheval.webp" alt="Cheval noir de profil"><svg viewBox="0 0 1000 563" aria-label="RepÃ¨res anatomiques"><line x1="825" y1="65" x2="690" y2="115"/><rect x="825" y="35" width="115" height="42" rx="12"/><text x="846" y="63">TÃªte</text><line x1="765" y1="167" x2="610" y2="180"/><rect x="765" y="138" width="150" height="42" rx="12"/><text x="780" y="166">Encolure</text><line x1="380" y1="165" x2="465" y2="205"/><rect x="215" y="135" width="105" height="42" rx="12"/><text x="238" y="163">Dos</text><line x1="120" y1="250" x2="288" y2="260"/><rect x="20" y="220" width="110" height="42" rx="12"/><text x="35" y="248">Croupe</text><line x1="770" y1="470" x2="560" y2="425"/><rect x="770" y="450" width="135" height="42" rx="12"/><text x="786" y="478">Membres</text></svg><figcaption class="anatomy-note">TÃªte : Ã  lâ€™avant ; encolure : entre tÃªte et garrot ; dos : entre garrot et reins ; croupe : Ã  lâ€™arriÃ¨re avant la queue ; membres : les quatre jambes.</figcaption></figure>`;

const f=document.createElement('link');f.rel='stylesheet';f.href='https://fonts.googleapis.com/css2?family=DM+Sans:wght@500;600;700&display=swap';document.head.appendChild(f);document.head.insertAdjacentHTML('beforeend',`<style>.nav a{font-family:'DM Sans',Arial,sans-serif!important;font-size:14px!important;letter-spacing:.03em!important;text-transform:uppercase!important}.nav .wrap{gap:4px}.nav a{border-radius:7px;margin:5px 0;padding:10px 13px!important}.nav a:hover{background:#edf2ea}.anatomy-clean img{display:block;width:100%;max-height:520px;object-fit:cover}.anatomy-clean{background:#fff;border:1px solid #d7e0d5;border-radius:16px;overflow:hidden}.anatomy-copy{padding:22px;display:flex;justify-content:space-between;align-items:center;gap:20px}.anatomy-copy p{margin:0;color:#63756a}@media(max-width:600px){.anatomy-copy{display:block}.anatomy-copy a{margin-top:14px}}</style>`);document.querySelector('#anatomie .wrap').innerHTML=`<div class="head"><h2>Anatomie du cheval</h2><p>Une photo sans repÃ¨res superposÃ©s, suivie dâ€™un guide complet Ã  consulter.</p></div><div class="anatomy-clean"><img src="assets/anatomie-cheval.webp" alt="Cheval noir de profil"><div class="anatomy-copy"><p>DÃ©couvrez toutes les parties du corps du cheval, avec une explication simple pour chacune.</p><a class="btn" href="anatomie.html">Ouvrir le guide dâ€™anatomie â†’</a></div></div>`;

const explorer=document.querySelector('.hero .btn');if(explorer){explorer.insertAdjacentHTML('afterend','<a class="btn credit-btn" href="credits.html">CrÃ©dits photos</a>');document.head.insertAdjacentHTML('beforeend','<style>.hero .credit-btn{margin-left:10px;background:transparent!important;border:1px solid #fff!important}.hero .credit-btn:hover{background:#fff!important;color:#234238!important}@media(max-width:500px){.hero .credit-btn{display:inline-block;margin:10px 0 0}}</style>')}

const horseClassic=document.querySelector('#eq-cheval .equip-card:first-child img');if(horseClassic){horseClassic.src='assets/equip-cheval-classique.png';horseClassic.alt='Cheval Ã©quipÃ© en Ã©quitation classique'}const riderWestern=document.querySelector('#eq-cavalier .equip-card:nth-child(2) img');if(riderWestern){riderWestern.src='assets/equip-cavaliere-western.png';riderWestern.alt='CavaliÃ¨re en tenue western'}document.head.insertAdjacentHTML('beforeend','<style>.equipment-summary{background:#edf2ea}.summary-box{display:grid;grid-template-columns:340px 1fr;gap:28px;align-items:center;background:#fff;border:1px solid #d7e0d5;border-radius:16px;overflow:hidden}.summary-box img{width:100%;height:480px;object-fit:cover;object-position:top}.summary-box div{padding:25px}.summary-box h2{color:#234238;font-size:38px;margin:0 0 12px}@media(max-width:720px){.summary-box{grid-template-columns:1fr}.summary-box img{height:auto;max-height:600px;object-fit:contain}}</style>');const sum=document.createElement('section');sum.className='section equipment-summary';sum.innerHTML='<div class="wrap"><div class="summary-box"><img src="assets/resume-equipement.png" alt="RÃ©sumÃ© des Ã©quipements dâ€™Ã©quitation classique"><div><h2>RÃ©sumÃ© Ã©quipement</h2><p>Un aperÃ§u visuel des Ã©lÃ©ments de base pour le cheval et le cavalier : casque, bride, selle, tapis, Ã©triers, pantalon, bottes et protections.</p><p class="subtle">CrÃ©dit photo : Pinterest â€” lien indiquÃ© dans les crÃ©dits photos.</p><a class="btn" href="credits.html">Voir les crÃ©dits photos â†’</a></div></div></div>';document.getElementById('anatomie').insertAdjacentElement('afterend',sum);

const anatomyImage=document.querySelector('#anatomie .anatomy-clean img');if(anatomyImage){anatomyImage.src='assets/anatomie-cheval.png';anatomyImage.alt='Cheval pie de profil pour le guide dâ€™anatomie'}

const localeBar=document.createElement('div');localeBar.className='locale-bar';localeBar.innerHTML='<label for="locale">Langue</label><select id="locale"><option value="fr-FR">FranÃ§ais (France)</option><option value="fr-CA">FranÃ§ais (Canada)</option><option value="en-US">English (USA)</option></select>';document.querySelector('.top').append(localeBar);document.head.insertAdjacentHTML('beforeend','<style>.top{position:relative}.locale-bar{position:absolute;right:24px;top:5px;display:flex;align-items:center;gap:7px;font:600 11px Manrope,Arial;color:#fff}.locale-bar select{background:#fffdf8;color:…17455 tokens truncated…blier la rÃ©ponse</button>';button.closest('.comment').append(reply);reply.querySelector('button').onclick=()=>send({preventDefault(){},currentTarget:reply},button.dataset.replyComment,current)});
    }
    async function send(event,parentId,current){event.preventDefault();const scope=event.currentTarget;const fields=scope.querySelectorAll('input,textarea');const pseudo=parentId?'DicoCheval':fields[0].value.trim();const contenu=parentId?fields[0].value.trim():fields[1].value.trim();const info=scope.querySelector('.comment-info');const reserved=String(pseudo||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'').includes('dicocheval');if(current.id!==OWNER&&reserved){if(info)info.textContent='Ce pseudo ne peut pas Ãªtre utilisÃ©.';return}if(!contenu)return;if(info)info.textContent='Publicationâ€¦';const payload={actualite_id:articleId,auteur_id:current.id,pseudo:current.id===OWNER?'DicoCheval':pseudo||'Visiteur',avatar_url:current.user_metadata?.avatar_url||null,contenu,parent_id:parentId};let {error}=await db.from('commentaires').insert(payload);if(error&&/avatar_url/i.test(error.message)){delete payload.avatar_url;({error}=await db.from('commentaires').insert(payload))}if(error){if(info)info.textContent='Impossible de publier ce commentaire.';return}load()}
    await load();
  }
  async function sync(force=false){document.querySelectorAll('.news-card[data-article-id]').forEach(card=>{if(force===true)card.querySelector('.official-comments')?.remove();mount(card)})}
  const newsListForComments=document.getElementById('newsList');if(newsListForComments)new MutationObserver(()=>sync()).observe(newsListForComments,{childList:true});db.auth.onAuthStateChange(()=>setTimeout(()=>sync(true),0));sync();
})();
/* AccÃ¨s rapides Ã  cÃ´tÃ© de la recherche. */
(() => {
  const wrap=document.querySelector('.search .wrap');
  if(!wrap)return;
  document.head.insertAdjacentHTML('beforeend','<style>.top-account-actions{display:flex;gap:7px;align-items:center}.top-account-actions .btn{padding:10px 12px;font-size:12px;white-space:nowrap}@media(max-width:720px){.search .wrap{flex-wrap:wrap}.search input{min-width:100%}.top-account-actions{width:100%}.top-account-actions .btn{flex:1}}</style>');
  const actions=document.createElement('div');actions.className='top-account-actions';actions.innerHTML='<button class="btn" id="topOwnerAccess">Espace propriÃ©taire</button><button class="btn" id="topVisitorAccess">Se connecter visiteur</button>';
  wrap.append(actions);
  const ownerButton=document.getElementById('topOwnerAccess'),visitorButton=document.getElementById('topVisitorAccess');
  const db=window.supabase.createClient('https://mmxdlnfntpufwwkdvgzc.supabase.co','sb_publishable_Pa-DX3nwNTZktbWK46KDQg_IuIy8TZP');
  const OWNER='f22161e4-7528-4fd2-9860-a18be084b1f6';
  function labels(){const en=document.getElementById('languageHero')?.value==='en';ownerButton.textContent=en?'Owner area':'Espace propriÃ©taire';visitorButton.textContent=en?'Visitor sign in':'Se connecter visiteur'}
  async function updateAccess(){labels();const {data}=await db.auth.getUser();if(!data.user)return;if(data.user.id===OWNER)ownerButton.textContent=document.getElementById('languageHero')?.value==='en'?'Owner connected':'PropriÃ©taire connectÃ©e';else visitorButton.textContent=document.getElementById('languageHero')?.value==='en'?'My account':'Mon compte'}
  async function openVisitorAccount(){const {data}=await db.auth.getUser(),modal=document.getElementById('commentAuthModal');if(!data.user){modal?.classList.add('open');return}const box=modal?.querySelector('.auth-box');if(!box)return;box.querySelectorAll('label,input,.comment-auth').forEach(el=>el.hidden=true);let account=document.getElementById('visitorAccount');if(!account){account=document.createElement('div');account.id='visitorAccount';box.append(account)}account.hidden=false;account.innerHTML='';const title=document.createElement('p');title.className='comment-info';title.textContent='Tu es connectÃ©e avec : '+(data.user.email||'ton compte')+'. Tu peux maintenant commenter les actualitÃ©s.';const signOut=document.createElement('button');signOut.className='btn';signOut.textContent='Se dÃ©connecter';signOut.onclick=async()=>{await db.auth.signOut();account.hidden=true;box.querySelectorAll('label,input,.comment-auth').forEach(el=>el.hidden=false);modal.classList.remove('open');updateAccess()};account.append(title,signOut);modal.classList.add('open')}
  ownerButton.onclick=()=>document.getElementById('ownerButton')?.click();
  visitorButton.onclick=openVisitorAccount;
  db.auth.onAuthStateChange(()=>setTimeout(updateAccess,0));document.getElementById('languageHero')?.addEventListener('change',updateAccess);updateAccess();
})();
/* Bouton Å“il pour afficher ou masquer les mots de passe. */
(() => {
  document.head.insertAdjacentHTML('beforeend','<style>.password-wrap{position:relative}.password-wrap input{padding-right:48px!important}.password-visibility{position:absolute;right:7px;top:50%;transform:translateY(-50%);padding:5px 7px!important;background:transparent!important;color:#234238!important;font-size:18px!important;line-height:1}</style>');
  function addEye(id){const input=document.getElementById(id);if(!input||input.dataset.eye)return;input.dataset.eye='true';const wrap=document.createElement('div');wrap.className='password-wrap';input.parentNode.insertBefore(wrap,input);wrap.append(input);const button=document.createElement('button');button.type='button';button.className='password-visibility';button.setAttribute('aria-label','Afficher le mot de passe');button.textContent='â—‰';button.onclick=()=>{const visible=input.type==='text';input.type=visible?'password':'text';button.textContent=visible?'â—‰':'â—‰Ì¸';button.setAttribute('aria-label',visible?'Afficher le mot de passe':'Masquer le mot de passe')};wrap.append(button)}
  addEye('securePassword');addEye('commentPassword');
})();

/* Recherche de membres : profils publics, sans e-mail. */
(() => {
  const db=window.supabase.createClient('https://mmxdlnfntpufwwkdvgzc.supabase.co','sb_publishable_Pa-DX3nwNTZktbWK46KDQg_IuIy8TZP');
  const input=document.getElementById('find'),button=document.querySelector('.search button'),wrap=document.querySelector('.search .wrap');
  if(!input||!button||!wrap)return;
  document.head.insertAdjacentHTML('beforeend','<style>.member-search-results{position:absolute;top:calc(100% + 5px);left:0;right:0;z-index:80;display:none;background:#fffdf8;border:1px solid #cbd8ce;border-radius:10px;box-shadow:0 10px 28px #17352624;padding:8px}.member-search-results.open{display:block}.member-search-title{font-size:12px;font-weight:800;color:#52685d;padding:5px 7px}.member-search-card{display:flex;align-items:center;gap:10px;width:100%;background:transparent!important;color:#24362e!important;border:0!important;text-align:left;padding:9px 7px!important}.member-search-card:hover{background:#edf2ea!important}.member-search-avatar{width:40px;height:40px;border-radius:50%;object-fit:cover;background:#dfe9df}.member-search-meta{font-size:12px;color:#63756a}.search .wrap{position:relative}</style>');
  const results=document.createElement('div');results.id='memberSearchResults';results.className='member-search-results';wrap.append(results);
  const esc=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const english=()=>document.getElementById('languageHero')?.value==='en';
  const defaultAvatar='assets/avatar-0.png';
  async function syncPublicProfile(user){
    if(!user)return;
    const m=user.user_metadata||{},points=Number(m.points||0);
    await db.from('profils_publics').upsert({id:user.id,pseudo:user.id==='f22161e4-7528-4fd2-9860-a18be084b1f6'?'DicoCheval':(m.pseudo||'Visiteur'),avatar_url:m.avatar_url||defaultAvatar,points,badges:Array.isArray(m.badges)?m.badges:[],membre_depuis:user.created_at},{onConflict:'id'});
  }
  async function searchMembers(){
    const term=input.value.trim();
    results.classList.remove('open');results.innerHTML='';
    if(term.length<1)return;
    const {data,error}=await db.from('profils_publics').select('pseudo,avatar_url,points,membre_depuis,badges').ilike('pseudo',term.replace(/[%_]/g,'')+'%').order('points',{ascending:false}).limit(7);
    if(error||!data?.length)return;
    const title=english()?'Member profiles':'Profils de membres';
    results.innerHTML='<div class="member-search-title">'+title+'</div>'+data.map(p=>{
      const joined=new Intl.DateTimeFormat(english()?'en-US':'fr-CA',{year:'numeric',month:'long',day:'numeric'}).format(new Date(p.membre_depuis));
      const labels=english()?(p.points+' points Â· Member since '+joined):(p.points+' point'+(p.points===1?'':'s')+' Â· Membre depuis le '+joined);
      return '<button type="button" class="member-search-card" data-member-name="'+esc(p.pseudo)+'"><img class="member-search-avatar" src="'+esc(p.avatar_url||defaultAvatar)+'" alt=""><span><b>'+esc(p.pseudo)+'</b><br><span class="member-search-meta">'+esc(labels)+'</span></span></button>';
    }).join('');
    results.classList.add('open');
  }
  const priorSearch=button.onclick;
  button.onclick=event=>{priorSearch?.call(button,event);searchMembers()};
  document.addEventListener('keydown',event=>{if(event.key==='Enter'&&document.activeElement===input)setTimeout(searchMembers,0)},true);
  document.addEventListener('click',event=>{if(!wrap.contains(event.target))results.classList.remove('open')});
  db.auth.getUser().then(({data})=>syncPublicProfile(data.user));
  db.auth.onAuthStateChange((_event,session)=>syncPublicProfile(session?.user));
})();


/* Suggestions pendant la recherche : membres. */
(() => {
  const db=window.supabase.createClient('https://mmxdlnfntpufwwkdvgzc.supabase.co','sb_publishable_Pa-DX3nwNTZktbWK46KDQg_IuIy8TZP');
  const input=document.getElementById('find'),box=document.getElementById('memberSearchResults');
  if(!input||!box)return;
  const esc=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const en=()=>document.getElementById('languageHero')?.value==='en';
  let timer;
  input.addEventListener('input',()=>{
    clearTimeout(timer);
    const query=input.value.trim().replace(/[%_]/g,'');
    if(!query){box.classList.remove('open');return}
    timer=setTimeout(async()=>{
      const {data,error}=await db.from('profils_publics').select('pseudo,avatar_url,points,membre_depuis,badges').ilike('pseudo',query+'%').order('points',{ascending:false}).limit(6);
      if(error||!data?.length)return;
      const userLabel=en()?'User':'Utilisateur',sinceLabel=en()?'Member since ':'Membre depuis le ';
      box.innerHTML='<div class="member-search-title">'+(en()?'Suggestions':'Suggestions')+'</div>'+data.map(p=>{
        const joined=new Intl.DateTimeFormat(en()?'en-US':'fr-CA',{year:'numeric',month:'short',day:'numeric'}).format(new Date(p.membre_depuis));
        return '<button type="button" class="member-search-card" data-member-name="'+esc(p.pseudo)+'"><img class="member-search-avatar" src="'+esc(p.avatar_url||'assets/avatar-0.png')+'" alt=""><span><b>'+esc(p.pseudo)+'</b> <small>Â· '+userLabel+'</small><br><span class="member-search-meta">'+p.points+' '+(en()?'points':'points')+' Â· '+sinceLabel+joined+'</span></span></button>';
      }).join('');
      box.classList.add('open');
    },220);
  });
})();


/* Ouvrir la page d'un membre depuis les suggestions. */
(() => {
  const box=document.getElementById('memberSearchResults');
  if(!box)return;
  box.addEventListener('click',event=>{
    const card=event.target.closest('[data-member-name]');
    if(!card)return;
    location.href='membre.html?pseudo='+encodeURIComponent(card.dataset.memberName);
  });
})();


/* Bouton de communautÃ© Discord. */
(() => {
  const language=document.getElementById('languageHero');
  if(!language||document.getElementById('communityButton'))return;
  const button=document.createElement('a');
  button.id='communityButton';
  button.className='btn community-button';
  button.href='https://discord.gg/wVpQHHZUE7';
  button.target='_blank';
  button.rel='noopener noreferrer';
  language.insertAdjacentElement('afterend',button);
  const label=()=>button.textContent=language.value==='en'?'Join the community':'Rejoindre la communautÃ©';
  language.addEventListener('change',label);label();
  document.head.insertAdjacentHTML('beforeend','<style>.community-button{margin-left:10px;background:transparent!important;border:1px solid #fff!important;text-decoration:none;display:inline-block}.community-button:hover{background:#fff!important;color:#234238!important}@media(max-width:500px){.community-button{margin:10px 0 0;display:block;width:max-content}}</style>');
})();


/* AccÃ¨s au profil depuis l'avatar d'un commentaire. */
(() => {
  document.addEventListener('click',event=>{
    const avatar=event.target.closest('.comment-avatar');
    if(!avatar)return;
    const comment=avatar.closest('.comment');
    const name=comment?.querySelector('b')?.textContent?.trim()||(comment?.querySelector('.official-badge')?'DicoCheval':'');
    if(name)location.href='membre.html?pseudo='+encodeURIComponent(name);
  });
})();

/* RÃ©sultat complet du quiz et meilleure note. */
(() => {
  const db = window.supabase?.createClient('https://mmxdlnfntpufwwkdvgzc.supabase.co','sb_publishable_Pa-DX3nwNTZktbWK46KDQg_IuIy8TZP');
  let score = 0, answered = 0, locked = false, timer;
  const english = () => document.getElementById('languageHero')?.value === 'en';
  const txt = (fr,en) => english() ? en : fr;
  const questions = () => english() && typeof enQuiz !== 'undefined' ? enQuiz : qs;
  const localBest = () => { try { return JSON.parse(localStorage.getItem('dcBestQuizScore') || 'null'); } catch { return null; } };
  const better = (next, previous) => !previous || next.percentage > previous.percentage || (next.percentage === previous.percentage && next.correct > previous.correct);
  async function saveBest(next) { const previous = localBest(); if (!better(next, previous)) return previous; localStorage.setItem('dcBestQuizScore', JSON.stringify(next)); window.dispatchEvent(new CustomEvent('dc-quiz-score-changed', {detail:next})); if (!db) return next; const {data} = await db.auth.getUser(); const user = data.user, saved = user?.user_metadata?.best_quiz_score; if (user && better(next, saved)) await db.auth.updateUser({data:{best_quiz_score:next}}); return next; }
  function finished(total) { const percentage = Math.round(score / total * 100), current = {correct:score,total,percentage,completed_at:new Date().toISOString()}, previous = localBest(), best = better(current,previous) ? current : previous; document.getElementById('qn').textContent = total; document.getElementById('question').textContent = txt('Quiz terminÃ© !','Quiz complete!'); document.getElementById('answers').innerHTML = ''; document.getElementById('result').innerHTML = `<strong>${txt('Ton rÃ©sultat','Your result')} : ${score} / ${total} (${percentage} %)</strong><br>${txt('Meilleur score','Best score')} : ${best?.correct ?? score} / ${best?.total ?? total} (${best?.percentage ?? percentage} %)`; saveBest(current); }
  function drawScoredQuiz() { clearTimeout(timer); const list = questions(); if (answered >= list.length) { finished(list.length); return; } const question = list[qi % list.length]; locked = false; document.getElementById('qn').textContent = answered + 1; document.getElementById('question').textContent = question[0]; document.getElementById('result').textContent = ''; document.getElementById('answers').innerHTML = question[1].map((choice,index)=>`<button type="button" data-choice="${index}">${choice}</button>`).join(''); document.querySelectorAll('#answers button').forEach(button=>button.onclick=()=>{ if(locked)return; locked=true; const correct=question[1][Number(button.dataset.choice)]===question[2]; if(correct)score+=1; answered+=1; document.querySelectorAll('#answers button').forEach(item=>item.disabled=true); document.getElementById('result').textContent=correct?txt('âœ“ Bravo, tu as rÃ©ussi !','âœ“ Well done, you got it!'):txt('âœ• RÃ©ponse : ','âœ• Answer: ')+question[2]; timer=setTimeout(()=>{qi=(qi+1)%list.length;drawScoredQuiz()},2000); }); }
  function restart() { clearTimeout(timer); qi=0; score=0; answered=0; drawScoredQuiz(); }
  setTimeout(()=>{ window.drawQ=drawScoredQuiz; window.nextQ=()=>{}; const restartButton=document.getElementById('restartQuiz'); if(restartButton)restartButton.onclick=restart; document.getElementById('languageHero')?.addEventListener('change',()=>{if(restartButton)restartButton.textContent=txt('Recommencer le quiz','Restart quiz');restart()}); drawScoredQuiz(); },0);
})();

/* Validation de Mon cheval idÃ©al et meilleur score dans le profil. */
(() => {
  const db = window.supabase?.createClient('https://mmxdlnfntpufwwkdvgzc.supabase.co','sb_publishable_Pa-DX3nwNTZktbWK46KDQg_IuIy8TZP');
  const english = () => document.getElementById('languageHero')?.value === 'en';
  const txt = (fr,en) => english() ? en : fr;
  function showBest() { const points=document.getElementById('memberPoints'); if(!points||document.getElementById('memberBestQuiz'))return; const line=document.createElement('p'); line.id='memberBestQuiz'; line.className='member-status'; const show=best=>{line.textContent=best?`${txt('Meilleur score au quiz','Best quiz score')} : ${best.correct} / ${best.total} (${best.percentage} %)`:txt('Meilleur score au quiz : aucun quiz terminÃ© pour le moment.','Best quiz score: no completed quiz yet.');}; try{show(JSON.parse(localStorage.getItem('dcBestQuizScore')||'null'))}catch{show(null)}; points.after(line); db?.auth.getUser().then(({data})=>{const best=data.user?.user_metadata?.best_quiz_score;if(best){line.textContent=`${txt('Meilleur score au quiz','Best quiz score')} : ${best.correct} / ${best.total} (${best.percentage} %)`}}); }
  setTimeout(()=>{ const button=document.querySelector('.ideal-submit'); const kg=document.getElementById('idealWeightKg'), cm=document.getElementById('idealHeightCm'); if(button&&kg&&cm){kg.required=true;cm.required=true;let last='';document.addEventListener('click',event=>{if(event.target!==button)return;const signature=[kg.value,cm.value,document.getElementById('ideal0')?.value,document.getElementById('ideal1')?.value,document.getElementById('ideal2')?.value].join('|'),result=document.querySelector('.ideal-result');if(!Number(kg.value)||!Number(cm.value)||!kg.checkValidity()||!cm.checkValidity()){event.preventDefault();event.stopImmediatePropagation();result.replaceChildren();const warning=document.createElement('p');warning.className='ideal-advice';warning.textContent=txt("Tu n'as pas rempli toutes les informations : indique ton poids et ta taille avant de trouver tes races.",'You have not completed all the information: enter your weight and height before finding your breeds.');result.append(warning);return}if(signature===last&&result.children.length){event.preventDefault();event.stopImmediatePropagation();return}last=signature;setTimeout(()=>{const note=document.createElement('p');note.className='ideal-advice';note.textContent=txt('Ces rÃ©sultats sont des pistes de compatibilitÃ© Ã  confirmer avec un moniteur ou un professionnel, selon le cheval prÃ©cis, sa morphologie, son niveau et son Ã©ducation.','These results are compatibility suggestions to confirm with an instructor or professional, based on the individual horse, its build, training and education.');if(!result.querySelector('.professional-note')){note.classList.add('professional-note');result.prepend(note)}},0)},true);}
    document.getElementById('topVisitorAccess')?.addEventListener('click',()=>setTimeout(showBest,100)); window.addEventListener('dc-quiz-score-changed',()=>{document.getElementById('memberBestQuiz')?.remove();showBest()});
  },0);
})();
