(() => {
  const titles=['Bien manger','Suivi vétérinaire','Hygiène et pelage','Bouger et jouer','Émotions et repos','S’adapter à la météo'];
  document.querySelectorAll('.mission h2').forEach((heading,index)=>heading.textContent=titles[index]||heading.textContent.replace(/^Mission\s+/i,''));
  const top=document.querySelector('.top'),lang=document.createElement('select');
  lang.id='careLanguage';lang.setAttribute('aria-label','Langue');lang.innerHTML='<option value="fr">Français</option><option value="en">English</option>';lang.value=localStorage.getItem('dicopetsLanguage')==='en'?'en':'fr';top.appendChild(lang);
  const style=document.createElement('style');style.textContent='#careLanguage{padding:10px 14px;border:1px solid #ffffff66;border-radius:999px;background:#fff;color:#173b30;font-weight:900}#careLanguage option{background:#fff;color:#173b30}';document.head.appendChild(style);
  const tr={
    'DicoPets · DicoChien':'DicoPets · DicoDog','← Retour à DicoChien':'← Back to DicoDog','Communauté':'Community','Prendre soin de son chien':'Caring for your dog','Prendre soin d’un chien, ce n’est pas seulement aller chez le vétérinaire. Découvre six repères simples pour l’aider à rester bien dans ses pattes.':'Caring for a dog is about more than veterinary visits. Discover six simple ways to help your dog stay healthy and happy.',
    'Bien manger':'Healthy eating','Suivi vétérinaire':'Veterinary care','Hygiène et pelage':'Hygiene and coat','Bouger et jouer':'Exercise and play','Émotions et repos':'Emotions and rest','S’adapter à la météo':'Weather safety',
    'Une ration adaptée à son âge et son poids':'Food suited to age and weight','De l’eau fraîche accessible':'Fresh water at all times','Une transition progressive lors d’un changement':'A gradual transition when food changes','Examen préventif régulier':'Regular preventive check-ups','Vaccins selon son mode de vie':'Vaccines suited to lifestyle','Protection contre les parasites':'Parasite prevention','Dents, oreilles et peau surveillées':'Check teeth, ears and skin','Griffes gardées à une bonne longueur':'Keep nails at a healthy length','Pelage brossé selon ses besoins':'Brush the coat as needed','Sorties adaptées à sa santé':'Outings suited to health','Jeux de flair et réflexion':'Scent and thinking games','Repos après l’activité':'Rest after activity','Un endroit calme pour dormir':'A quiet place to sleep','Des apprentissages sans violence':'Kind, force-free learning','Du temps avec ses humains':'Time with their people','Éviter l’effort pendant la chaleur':'Avoid exertion in hot weather','Protéger les coussinets du froid':'Protect paw pads from cold','Adapter la durée des sorties':'Adjust the length of outings',
    'Ma vérification express':'My quick check','Coche ce que tu as vérifié aujourd’hui. La liste recommence chaque fois que tu ouvres la page.':'Check what you reviewed today. The list starts fresh each time you open the page.','Eau propre':'Clean water','Appétit normal':'Normal appetite','Belle énergie':'Healthy energy','Peau et pelage normaux':'Healthy skin and coat','Selles normales':'Normal stools','Moment calme et heureux':'Calm and happy time',
    'Ouvre une question 👇':'Open a question 👇','Combien d’activité faut-il?':'How much activity is needed?','Cela dépend de l’âge, de la santé, de la race et du caractère. Une sortie tranquille, du flair et de petits apprentissages peuvent être aussi utiles qu’une activité très intense.':'It depends on age, health, breed and personality. A calm walk, scent games and short training sessions can be as useful as intense exercise.','Comment savoir si son poids convient?':'How can I tell if the weight is healthy?','On doit généralement pouvoir sentir les côtes sans appuyer fortement et voir une taille derrière les côtes. Le vétérinaire peut confirmer l’état corporel idéal.':'You should usually be able to feel the ribs without pressing hard and see a waist behind them. A veterinarian can confirm ideal body condition.','Pourquoi entretenir les dents?':'Why care for the teeth?','La plaque et le tartre peuvent provoquer douleur et maladie. Demande au vétérinaire une méthode adaptée avant de commencer.':'Plaque and tartar can cause pain and disease. Ask a veterinarian about a suitable method before starting.','🚨 Quand consulter rapidement?':'🚨 When is urgent care needed?','Difficulté à respirer, convulsions, perte de conscience, ventre soudainement gonflé, douleur intense, saignement important ou ingestion possible d’un produit toxique nécessitent un appel vétérinaire urgent.':'Breathing difficulty, seizures, loss of consciousness, sudden abdominal swelling, severe pain, major bleeding or possible toxin ingestion require an urgent veterinary call.','Important :':'Important:','cette page aide à apprendre, mais elle ne remplace jamais un diagnostic ou un traitement vétérinaire.':'this page supports learning but never replaces veterinary diagnosis or treatment.'
  };
  const originals=new WeakMap();function walk(node,en){if(node.nodeType===3){if(!node.nodeValue.trim())return;if(!originals.has(node))originals.set(node,node.nodeValue);const fr=originals.get(node),key=fr.trim(),lead=fr.match(/^\s*/)[0],tail=fr.match(/\s*$/)[0];node.nodeValue=en?lead+(tr[key]||key)+tail:fr;return}node.childNodes.forEach(n=>walk(n,en))}
  function apply(){const en=lang.value==='en';localStorage.setItem('dicopetsLanguage',en?'en':'fr');document.documentElement.lang=en?'en':'fr';document.title=en?'Dog care and health · DicoPets':'Soins et santé du chien · DicoPets';walk(document.body,en)}lang.onchange=apply;apply();
})();
